### ISSUE TITLE
Causes error for saving new ACF field groups 

### ISSUE THREAD

**Issue by jcklpe** [getblocklab/block-lab#103]
This seemed to work fine on my old portfolio website, but when I tried creating some custom fields using ACF with this installed today I kept getting an error. When I turned off this plugin it worked fine. I then created my fields, and then turned it back on. Seems to work fine that way. But also kind of a work around and figured you guys should know. Thanks.

**Comment by lukecarbis** [comment]
@jcklpe I can't seem to replicate this on the latest version of both plugins. Could you please take a fresh look and see if it's still a problem? Here's my attempt: https://drive.google.com/file/d/1ZMEwpp0tgG5J4uC9cMvYZ4z62R_CaBzR/view?usp=sharing

@RobStino It would be good to see if you can replicate the issue, too.

**Comment by jcklpe** [comment]
I will try to once I get a version of my website spun up. Right now running into some problems with how I backed up things and trying to untangle the mess I made.

**Comment by RobStino** [comment]
I've tested this as well and can't replicate the issue. @jcklpe If you get a chance to test again, let us now how you go.
@lukecarbis FWIW the toggle fields worked ok for me in ACF.

**Comment by lukecarbis** [comment]
Closing for now.
