### ISSUE TITLE
The admin menu item for Block Lab doesn't appear after plugin activation

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#106]
The menu item appears after a browser refresh.
Standard experience is it should appear immediately after activation.

**Comment by rheinardkorf** [comment]
Debatable if its "standard".  Expected, sure. Standard, not necessarily. 

The menu is added by `add_menu_page`, the rest is up to core to facilitate. Sometimes, however, plugin developers deliberately do a WordPress redirect upon activation to show the menu. This is a terrible idea.
