### ISSUE TITLE
Maybe required doesn't make sense.

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#113]
If I mark a field as required, I can still save my post. Do required fields even make sense? I'm not sure they do. Any thoughts @RobStino ?

**Comment by RobStino** [comment]
I think eventually. But perhaps not right now.
The user experience for this probably needs to be thought through more.

**Comment by RobStino** [comment]
I imagine that it would ultimately be more about whether the field value or block is rendered on the front end.
