### ISSUE TITLE
Losing all block fields and settings after adding and publishing a select field

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#120]
Steps to reproduce:
1. Create new block
2. Give name, slug, etc
3. Add some string based fields and publish (to confirm it's not text fields causing the issue)
4. Add a Select field and update

After the publish refresh, note that the configurations and added fields are all gone.

Note that prior to adding the select field, I could use the block in the GB editor. After I added the select field and updated, I couldn't use it in the GB editor.

**Comment by lukecarbis** [comment]
I can't replicate, but I did see this earlier (not sure if I was using Select or not). Keep an eye out and if you see it, try to get more exact steps to replicate it.
