### ISSUE TITLE
Additional global field options

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#13]
- Required
- Default value
- Field instructions

**Comment by rheinardkorf** [comment]
Required does not work for "SelectControl" "CheckboxControl", "ToggleControl" and "RadioControl".

**Comment by rheinardkorf** [comment]
Required is a boolean: `"required": true` , false by default.
Default is supplied using `"default": <value>`.
Field instructions is called `help` in Gutenberg, so option is `"help": "Some help"`

**Comment by lukecarbis** [comment]
That's a good point. Default value may not always work, either. I think that these should all be implemented outside of the abstract class, for two reasons:

1. More flexibility for controls to choose which "defaults" they include
2. More flexibility for controls to put options in the right order
