### ISSUE TITLE
Add Status (published, draft, etc) to Block table

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#138]
Seeing that we can now save blocks as a draft, it makes sense (maybe) adding a new column to the block table that shows the status.

**Comment by lukecarbis** [comment]
We already do this? Same as regular posts.

![screen shot 2018-11-15 at 2 11 40 pm](https://user-images.githubusercontent.com/1097667/48529801-7c44c480-e8e0-11e8-8ef5-c0486f293995.png)

**Comment by RobStino** [comment]
Ooooh!
