### ISSUE TITLE
`Warning: filemtime(): ...` displayed under the block content

### ISSUE THREAD

**Issue by delawski** [getblocklab/block-lab#147]
I've created a sample block called 'Subhead' consisting of a single textarea control.

**Issue:**
I'm getting the following error under the block content both in the editor and in the front-end:

`Warning: filemtime(): stat failed for /app/public/wp-content/plugins/block-lab/js/editor.blocks.js in /app/public/wp-content/plugins/block-lab/php/blocks/class-loader.php on line 78 Warning: filemtime(): stat failed for /app/public/wp-content/plugins/block-lab/css/blocks.editor.css in /app/public/wp-content/plugins/block-lab/php/blocks/class-loader.php on line 94`

**Screenshot:**
![screenshot 2018-11-16 18 57 53](https://user-images.githubusercontent.com/478735/48638940-57c91500-e9d2-11e8-86b0-75323ece08e4.png)

**Context:**
I've tried both cloning the repo from GitHub, running `npm install`, `npm run build` _and_ downloading the plugin directly from WordPress.org. In both cases I'm getting the warning.

**Comment by delawski** [comment]
The warning is gone now. I'm not sure what has cleared it. It seems it is a bug that shows up on a fresh install.

**Comment by RobStino** [comment]
Thanks for logging this @delawski 
Could you share the PHP etc version numbers this new install was running?

**Comment by delawski** [comment]
Sure, here's my local setup:

<img width="225" alt="screenshot 2018-11-17 15 15 42" src="https://user-images.githubusercontent.com/478735/48662009-b1394e80-ea7b-11e8-9c97-d8eb00c5eba4.png">
