### ISSUE TITLE
WordPress Import/Export file is empty

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#149]
When you use the standard WordPress import/export process (and plugin) for importing and exporting blocks, no blocks are imported/exported.
You can select Blocks as an option when exporting, much like you do other CPTs. An xml file is also able to be generated. This can be then imported, however no blocks are added to the site that is imported to.
Steps to reproduce:
1. Create a block
2. Tools>Export
3. Select the "Blocks" checkbox
4. Export .xml file
5. Import .xml file to new site
6. Go to Block Lab>All Blocks and note that imported block hasn't been imported.

**Comment by lukecarbis** [comment]
@RobStino Can you test again? Worked fine for me!

If you're still having problems, post your XML file, and also let me know if the import says "Failed" or simply "All done. Have fun!".
