### ISSUE TITLE
"Image" control type

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#15]
- Return value
  - Image object
  - Image url
  - Image ID

**Comment by rheinardkorf** [comment]
Oops... this one is not yet implemented!  Ignore the comment.

**Comment by jcklpe** [comment]
This is the number one custom field type I need aside from repeater.

**Comment by lukecarbis** [comment]
For the time being, you could drop a URL in as a text field.

**Comment by jcklpe** [comment]
@lukecarbis If I wanted to create a weird custom button that used a scrolling image background, I might want to expose the image as a field for the user to choose on a case by case base. That might seem a bit weird, but I can come with dozen of examples that I've done similar things with ACF at least. You could do with it a url if the image url is hardcoded into the template but you might want to also give the user the option of choosing.

**Comment by RobStino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Field - Media](https://trello.com/c/zWDy1rFm/15-new-field-media)

**Comment by digitall-it** [comment]
I second that request, a new field of type Media. It should come with cutting/resizing helper functions.

**Comment by MichaelEnkirch** [comment]
Whats the state here? The Trello Link is "empty". This is such a needed field!

**Comment by RobStino** [comment]
Hey all. :)
Working on this field right now! We were initially planning on having this released with the `Color` field, but didn't quite get there. Expect to see it within the next few weeks though.

_Sneak Peek_
![image](https://user-images.githubusercontent.com/1578148/51212006-e02c4d80-1962-11e9-8ece-3ad17bc813bc.png)
