### ISSUE TITLE
Requires PHP: 5.7

### ISSUE THREAD

**Issue by ghost** [getblocklab/block-lab#152]
Hey! There's no PHP version 5.7 😄 
It should be either 5.6 or 7.0

![2018-11-20_073944](https://user-images.githubusercontent.com/11320080/48753757-d86c6780-ec97-11e8-8a7d-3ff49b249274.jpg)

**Comment by lukecarbis** [comment]
😂 Ha! How did that get in there. I'll sort that out, thanks for the heads up.
