### ISSUE TITLE
Adding "quotes" in fields kills all fields and you have to start over

### ISSUE THREAD

**Issue by audetcameron** [getblocklab/block-lab#153]
Adding "quotes" in fields kills all fields and you have to start over.   Any way to add validation or  escapes \  before "  in a field?   I can look into it this weekend as well.

**Comment by RobStino** [comment]
Hey @audetcameron we have a PR just merged that should address this one. It should hit the wp.org repo in the next week or so, otherwise you can pull down the `develop` branch from here.

**Comment by lukecarbis** [comment]
Resolved in #154 .

**Comment by audetcameron** [comment]
> Hey @audetcameron we have a PR just merged that should address this one. It should hit the wp.org repo in the next week or so, otherwise you can pull down the `develop` branch from here.

fantastic!
