### ISSUE TITLE
Feature Request: link/url Picker

### ISSUE THREAD

**Issue by AdsonCicilioti** [getblocklab/block-lab#159]
For pick existents links from all published contents on wp site or external.
Same as link picker of ACF.
 
![image](https://user-images.githubusercontent.com/6278398/48881921-fdc7b580-edfe-11e8-8d72-3495de3998be.png)

Or a simple version:
![image](https://user-images.githubusercontent.com/6278398/48881975-32d40800-edff-11e8-8227-a0c7be121b02.png)

**Comment by RobStino** [comment]
Hi @AdsonCicilioti 
Thanks for dropping this in here.
Both a general URL field as well as a post (post, page, CPT) field are on our radar.
I imagine the general URL field won't be too far away.
Thanks for trying out the plugin. Hope it helps you out. :)

**Comment by AdsonCicilioti** [comment]
Great!

**Comment by lukecarbis** [comment]
Closed in favour of #19 .
