### ISSUE TITLE
Is there a way to export blocks to code?

### ISSUE THREAD

**Issue by ibes** [getblocklab/block-lab#179]
I gave block lab a test run and it seems like a very helpful and needed plugin to have around. 

I am used to using ACF (Advanced Custom Fields) which you likely know (if not - if would be good to get familiar with it). 

In ACF I can create Meta Fields similar to how I can create Blocks with Block Lab. 

When using ACF I always export my fields to code - even if I prefer to modify the fields in the GUI (and then export them again to code). 

Why?
1) It feels cleaner
2) I imagine it is faster as other ways the configuration first needs to be taken out of the database or loaded from a JSON file (I guess they have implemented that in a recent update). If it is exported to PHP it should already be in the form it will be used. 
3 ) and most important: **Version Control**

I guess that would also be a great thing for Blocks.

Yes, Block content belongs in the database as it is content and content is stored in the database.

But Block configuration is no content - so there is no need to keep it in the database. 
And there _is_ the need to be able to push it from development to live etc. and version control it. 

Your solution feels quite elegant and great. But without configuration to code, the plugin fails the use case of professional deployment setups, I guess. 

I saw a closed ticket about exporting blocks to stand alone plugins. #50 
If that is not just closed but noted down somewhere - that would be quite a game changer. As the Block might even work without block lab and so save a dependency. 
Downside: There is not an easy way to get new improvements from the generator plugin in the exported Block plugin without re-export the Block plugin.

But maybe there could be a thing where the Block could be re-exported from a config file or something. 

Anyway - awesome idea and what you have so far looks super needed. 

But: how to version control?

**Comment by lukecarbis** [comment]
Totally agree this should be surfaced in the UI. Right now, this feature _sort of_ exists. The `post_content` of a block is just json data, and if you throw that in a file in your child theme at `blocks/blocks.json`, then the blocks will exist in Gutenberg.

But this ticket stands aside from that feature, as we need to create a UI for importing and exporting.

**Comment by markusb** [comment]
I'm looking for the same functionality as well. I'd like to create a custom block and export it to a custom, self-contained plugin. So I can move the plugin to where I need it without prerequisites.

**Comment by ohlauren** [comment]
same!

**Comment by hacknug** [comment]
It seems to be possible to import/export if you have a Pro license. From [their recently updated site](https://getblocklab.com/block-lab-pro/) (got my newsletter just this morning):

> **Import / Export**
> Take your custom blocks wherever you need them. This Pro feature is ready now for Early Access pass holders.

**Comment by lukecarbis** [comment]
Yes, that's right. Import / Export are in the current Pro version. However, please note that this is a JSON export (to use a block on multiple sites), _not_ a code export.

**Comment by haicu** [comment]
Just curious. Is there any progress made on export to code yet?

**Comment by lukecarbis** [comment]
Yes – we experimented with a rudimentary prototype, but in the end decided to wait and see what WordPress Core's implementation of a Block Directory looks like, so that we can ensure that our exported blocks are compatible with that.

**Comment by kienstra** [comment]
**Good idea, but probably not practical now**

As Luke mentioned in https://github.com/getblocklab/block-lab/issues/179#issuecomment-468500730, there is a way to export block(s) to JSON, but that's not what this ticket is opened for.

Exporting PHP or JS code to be used independently of this plugin probably wouldn't be practical. It would probably mean forking much of the plugin.

Most of Block Lab's code is for rendering the fields in the block editor as a block. Unfortunately, there's no Core PHP function that does that which we could allow exporting. And there's no simple way to do that in JS, without forking much of the plugin.

Rendering the PHP template on the front-end is relatively simple. For example, you could reimplement a BL block `test-hero` as a [dynamic block](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/) with:

```.
add_action(
  'init',
  function() {
     register_block_type(
        'block-lab/test-hero',
        [
           'attributes' => [
              'headline' => [
                 'type' => 'string',
              ],
              ...
```

**Comment by kienstra** [comment]
Though this isn't the intent of this issue, it would be possible to add a feature to export the block via the [PHP function](https://getblocklab.com/building-custom-blocks-programmatically/) `block_lab_add_block()`.

So it would export a PHP file with something like:

```php
<?php

block_lab_add_block(
      'your-block',
      [
              ....
```

It would still require using Block Lab. But I think the PHP function is a much better way of reusing blocks across sites.

This is inspired by https://wordpress.org/support/topic/export-pro-vs-export-free/
