### ISSUE TITLE
Import / Export JSON file of blocks

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#18]
This is especially useful for theme authors who wish to use ACB to build blocks, and want to distribute the blocks with their themes.

**Comment by lukecarbis** [comment]
@rheinardkorf This is done, right?

**Comment by rheinardkorf** [comment]
@lukecarbis It uses `blocks.json` but it does not import it into the "Blocks" UI, but it does add it to Gutenberg.  How important is it to preserve the blocks if a user switches themes?  Because then we would need to import... and that is not done.

**Comment by lukecarbis** [comment]
In that case it should be Import (and export), not auto-import.

**Comment by rheinardkorf** [comment]
So this is not technically import functionality. It simply makes blocks available that are defined in `blocks.json`.  We would have to develop explicit import/export functionality and perhaps offer an option to import from a detected `blocks.json` file.  E.g.  "We detected `blocks.json` in your theme. Do you want to import these blocks?"
