### ISSUE TITLE
Multi-Select Control: "Undefined index: items" from rest-api.php

### ISSUE THREAD

**Issue by camya** [getblocklab/block-lab#195]
Hello,

I tested the new Multi-Select control implementation. Unfortunately I receive an error 
**"Notice: Undefined index: items"** from the Rest API. (See full error output below!)

### Field config:

**Choices:**

```
news : News
info : Info
update : Update
```

**Default value:**

`news`

### Error output

```
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1121</b>
{"rendered":"\r\n<h2>Just a box!<\/h2>\r\n\r\npre>\r\nbox-type:\r\narray(1) {\n  [0]=>\n  string(4) \"info\"\n}\n<\/pre>"}
```

**Comment by lukecarbis** [comment]
@greenphp Could you tell me how you're making the API call, what it looks like, what you're expecting, etc.?

**Comment by camya** [comment]
@lukecarbis I don't make the API call. Looks like its called automatically, if the block preview is build. But I'm still not sure, if this is only a problem in my environment.

At the moment, it looks like the `rest_validate_value_from_schema()` function  (See Line 1121 of `\wp-includes\rest-api.php`) needs `$args['items']` for the **type "array"**.

Because this is not set, I get the `<b>Notice</b>:  Undefined index: items` message.

### Output array in rest_validate_value_from_schema()

The error output is in line 1121, so I've added the dump in the `if ( 'array' === $args['type'] )` condition.

```
function rest_validate_value_from_schema( $value, $args, $param = '' ) {
if ( 'array' === $args['type'] ) {
  // DEBUG OUTPUT
  print_r($args); 
  ...
  ...
  foreach ( $value as $index => $v ) {
    // ERROR/NOTICE HERE
    $is_valid = rest_validate_value_from_schema( $v, $args['items'], $param . '[' . $index . ']' ); 
    ...
```

### The output:

The line number changed, because I added the print_r() ;) Without it, the warning is in line 1121.

```
Array
(
    [type] => array
    [default] => Array
        (
            [0] => news
        )

)
<br />
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1124</b><br />
Array
(
    [type] => array
    [default] => Array
        (
            [0] => news
        )

)
<br />
<b>Notice</b>:  Undefined index: items in <b>\wp-includes\rest-api.php</b> on line <b>1124</b><br />
{"rendered":"\r\n<h2>Just a box!<\/h2>\r\n\r\npre>\r\nbox-type:\r\narray(1) {\n  [0]=>\n  string(6) \"update\"\n}\n<\/pre>"}
```

**Choices:**

```
news : News
info : Info
update : Update
```

**Default value:**

`news`

**Comment by lukecarbis** [comment]
@greenphp Thanks for the detailed info. I can see the part of `rest_validate_value_from_schema` you mentioned.

I've setup a multiselect with the choices and default value you suggested, but can't replicate the problem. So far I've tried adding the block to a post, creating a template for the block, and checking it on the front end.

Can you please provide instructions on how to replicate the problem?

**Comment by camya** [comment]
@lukecarbis I'm working on a **local Dev-Enviroment** with default activated internal WordPress debug mode in wp-config.php (`define('WP_DEBUG', true);`) in order to see problems while developing a feature in PHP.  Maybe that's why you don't see the Error/Notice?

If I deactivate the debug mode, it looks like everything works fine. If I activate it, I receive the notice, which breaks the functionality of the block.

**Comment by lukecarbis** [comment]
Ah, yes, that's it. Didn't have `WP_DEBUG` on. Rookie mistake. I was able to replicate this.

**Comment by lukecarbis** [comment]
@greenphp I'm really sorry – I know we've been back and forth a lot already. I just circled back around to this, and of course, I'm having problems replicating it again.

I know we did a good amount of work on validating the output recently – could you please check to see if you're still affected by this issue?
