### ISSUE TITLE
"WYSIWYG" control type

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#20]
Shows a rich editor, including formatting controls.

**Comment by sanjay51** [comment]
Hi Luke, quick question: Is this happening anytime soon? 
Thank you.

**Comment by lukecarbis** [comment]
Hi @sanjay51 – this is likely to be one of the last control types we implement. The next release will include colour and (hopefully) media.

**Comment by ChrlyDevedson** [comment]
> Hi @sanjay51 – this is likely to be one of the last control types we implement. The next release will include colour and (hopefully) media.

That's too bad

**Comment by lukecarbis** [comment]
@sanjay51 @ChrlyDevedson I lie! Working on it now. Not as hard as I had anticipated.

**Comment by lukecarbis** [comment]
Closing in favour of #221.
