### ISSUE TITLE
Number field reverts to default value after refresh

### ISSUE THREAD

**Issue by annestk** [getblocklab/block-lab#203]
When using a block with the Number Field Type, it works as expected upon entering a number, updating, previewing etc.

But when I refresh the page/come back to edit the post, the number field has reverted to the default value.

I tried leaving the default value empty, but then it's set to 0 automatically (Kinda like #196 with multi-selects)

**Version:** I'm using WordPress 5.0 and BlockLab 1.1.0.

**Comment by lukecarbis** [comment]
Thanks for the bug report @annestk – will release a fix this week.

**Comment by annestk** [comment]
@lukecarbis great!

Thank you for making a tool that allows someone like me (who barely knows anything but HTML and CSS) to play with Gutenberg blocks 😄
