### ISSUE TITLE
Wrapper blocks

### ISSUE THREAD

**Issue by lmp-computopic** [getblocklab/block-lab#210]
How do can we wrap other blocks in our custom blocks?

I'd like to have a block type that simply creates a border around it's content (which can be other gutenberg blocks of content) - but I can't find a way to do this?

**Comment by audetcameron** [comment]
> How do can we wrap other blocks in our custom blocks?
> 
> I'd like to have a block type that simply creates a border around it's content (which can be other gutenberg blocks of content) - but I can't find a way to do this?

I ended up making a custom block that was just a string and in the string used my opening div  and another one with closing div below my blocks.

**Comment by lukecarbis** [comment]
That's not a bad workaround. Another could potentially be to "recreate" the blocks that you want wrapped, but include an option to add a border.

Besides this there's not any real way of doing that in the plugin at the moment, and we've not got any plans to introduce this.

**Comment by lmp-computopic** [comment]
@audetcameron - thanks for the workaround could you share a fairly complete example?
I'm new with WordPress (coming from Drupal among other things)

@lukecarbis - understandable - In my case I need a border around some elements + a Gutenberg provided button

**Comment by lmp-computopic** [comment]
@audetcameron - ah sorry - I get your idea now - thanks for the hint

**Comment by audetcameron** [comment]
Sure thing:     example:     In block lab I created a new block called htmlwrapper with a single text field called htmlwrappertag.      I created my block template 
```
<?php block_field('htmlwrappertag'); ?>
<code class="wrapperDivCodeClass">
<?php
	$mystring = esc_html(block_field('htmlwrappertag', $echo = false));
	echo 'Custom HTML Wrapper | ' . $mystring;
?>
</code>
```

Then in my main style.css I added
 ```
 .wrapperDivCodeClass{display:none;}
```
In functions .php I added 
```
//add custom function for admin only
add_action('admin_head', 'html_wrapper');
function html_wrapper() {
  echo '<style>
   .wrapperDivCodeClass{
    display:block;
   }
  </style>';
}
```

the extra little bit makes it so in the editor you can see the code  but the front end doesn't see it.

![wordpress-trick](https://user-images.githubusercontent.com/6738453/50297961-01754900-044c-11e9-8b38-c17ac632ce5a.gif)
