### ISSUE TITLE
Filter block_categories not working

### ISSUE THREAD

**Issue by gfazioli** [getblocklab/block-lab#213]
The following code seems not working for me:

```php
    add_filter('block_categories', function ($categories, $post) {
        return array_merge(
            $categories,
            [
                [
                    'slug' => 'my-slug',
                    'title' => 'my-title',
                    'icon' => null,
                ],
            ]
        );
    }, 10, 2);
```

are you using the filter above to get the categories block?

**Comment by lukecarbis** [comment]
Sorry! Really need to get in there and update the docs. Block categories can no longer be filtered because Gutenberg doesn't support custom categories anymore (or, at least, they're discouraged), so we removed that functionality from Block Lab.

**Comment by Jebble** [comment]
Gutenberg most certainly supports custom categories. the block_categories filter is documented and the custom categories are working on WP 5.0.2.

You should include custom categories in Block Lab

**Comment by lukecarbis** [comment]
@Jebble @gfazioli Ah, did some searching and found what you're talking about. Docs here: https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#managing-block-categories

It used to be that custom categories were defined during block registration. Turning on custom categories for Block Lab will require a creative workaround during the registration process to add the filter, but it's doable. I'll create an issue for it.
