### ISSUE TITLE
Custom block categories

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#215]
Support for, and ability to define, custom block categories.

https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#managing-block-categories

**Comment by x5hwuk7nc6jsudcc** [comment]
This would be great. We've modulated a recent design to about 20 blocks and being able to split these into 3-4 custom categories would be very helpful. Would love to see this in 1.4...
