### ISSUE TITLE
Add Block Icon to Properties panel

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#22]
The user should be able to choose from the Dashicons library. The options should be displayed visually, not as text from a dropdown menu.

Only dashicons for now.

**Comment by lukecarbis** [comment]
@RobStino Keen for a mockup on how this could work.

**Comment by RobStino** [comment]
![acb_block_icon_property_control](https://user-images.githubusercontent.com/1578148/43577909-9c820778-9690-11e8-906d-188e1e269806.png)
There were no obvious native solutions for this (apart from the Media Library modal), so I wanted to keep this as simple as possible as I imagine we'll be giving the UI design much more attention around v1.0.
