### ISSUE TITLE
Variable declarations appearing on Front End

### ISSUE THREAD

**Issue by marselgray** [getblocklab/block-lab#226]
When I declared some variables and then attempted to manipulate them, I noticed they were appearing in the Front End.

```
$video_one = block_field('video-one-url');
$split_one = substr($video_one, 32);
```

![screen shot 2019-01-31 at 8 37 12 am](https://user-images.githubusercontent.com/37955946/52057605-73ed4480-2533-11e9-89b5-fe41b5ff87a2.png)

I managed to hide them by wrapping them in a p tag with display: none; as the styles. But I'm wondering if there is 1) another way I am missing or 2) if this is an issue in Block Lab not yet realized.

**Comment by camya** [comment]
Hi @marselgray,

just replace block_field() with `block_value()` and it will work.

`$video_one = block_value('video-one-url');`

Use block_field() function only, if you want directly echo a Block Lab field.

**Comment by lukecarbis** [comment]
Thanks @greenphp – that's it exactly.

**Comment by marselgray** [comment]
Thank you so much for the help!
