### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by finnruijter** [getblocklab/block-lab#227]
I'm missing a lot of fields documentation in the Wiki. Fields like image for example.

**Comment by kadenmclaws** [comment]
I also have a request for a Documentation update. I am specifically trying to create a custom block that allows for addition CSS classes from the Gutenberg's block settings tab, under "Block" -> "Advanced" -> "Additional CSS Classes"

On displaying a block, there is the following example:

```
<img src="<?php block_field( 'profile-picture' ); ?>" alt="<?php block_field( 'author-name' ); ?>" />
<h3><?php block_field( 'author-name' ); ?></h3>
<p><?php block_field( 'testimonial' ); ?></p>
```

And I am looking for something such as:

```
<section class="<?php block_wrapper_classes( array('other-classes', 'can-be', 'included-also')); ?>">
   <img src="<?php block_field( 'profile-picture' ); ?>" alt="<?php block_field( 'author-name' ); ?>" />
   <h3><?php block_field( 'author-name' ); ?></h3>
   <p><?php block_field( 'testimonial' ); ?></p>
</section>
```

**Comment by lukecarbis** [comment]
@finnruijter Docs updated with all the latest blocks! Thanks for pushing me to do this.

@KillerPancakes Block Lab doesn't currently have a way of surfacing the data from the editor's native "Additional CSS Classes" field – but it should! I'll create a new issue for this.
