### ISSUE TITLE
No escaping in the docs

### ISSUE THREAD

**Issue by tomjn** [getblocklab/block-lab#228]
Every single example in the docs is missing escaping. Since users tend to copy the code in the docs to be sure they're doing things right, this means most people using block labs will be running insecure code, unawares.

For example in the `block_field` documentation there's an insecure code example:

```php
$url = block_field( 'url', false );

if ( ! empty( $url ) ) {
    echo '<a href="' . $url . '">Click me!</a>';
}
```

Which should be:

```php
$url = block_field( 'url', false );

if ( ! empty( $url ) ) {
    echo '<a href="' . esc_url( $url ) . '">Click me!</a>';
}
```

Every code example involving `echo` suffers the same security issue

**Comment by lukecarbis** [comment]
Yes, I've been very aware of that, but also trying to balance making the code as accessible as possible for those new to PHP. Trying to keep things simple. For example:

```PHP
<a href="<?php block_field( 'link' ); ?>" />
```

becomes

```PHP
<a href="<?php echo esc_url( block_value( 'link' ) ) ); ?>" />
```

Do you think adding a paragraph on escaping at the top of the page would be a good balance? Is there another solution?

**Comment by tomjn** [comment]
I think that have declarative functions that output is great, my only
concern is that the block_field function is unaware of its context and
can't guess the correct escaping function except in some cases

So instead Id suggest adding variants for various data types eh
block_field_attr block_field_url block_field_kses_post block_field_html etc

As for escaping I'd include it then say something like

"Notice the escaping function, don't forget to use escaping functions such
as these" and link off to a good resource, treat is as a learning
opportunity :) if they're super beginner they're probably copying the
entire thing anyway
