### ISSUE TITLE
Arabic script error

### ISSUE THREAD

**Issue by borayeris** [getblocklab/block-lab#229]
Error loading block: The response is not a valid JSON response.

**Comment by lukecarbis** [comment]
I'm having trouble replicating this error. Here's some screenshots of how I've got my block setup, and it seems to work fine.

![Screen Shot 2019-03-12 at 3 11 12 pm](https://user-images.githubusercontent.com/1097667/54176095-21f7f100-44d9-11e9-8b6b-ab4f5ca6c1cb.png)
![Screen Shot 2019-03-12 at 3 09 38 pm](https://user-images.githubusercontent.com/1097667/54176097-23291e00-44d9-11e9-827d-d458007f3a58.png)
![Screen Shot 2019-03-12 at 3 10 18 pm](https://user-images.githubusercontent.com/1097667/54176098-245a4b00-44d9-11e9-9711-295c78f52bfa.png)

Could you please provide more detailed instructions on how to go about replicating the issue?

**Comment by lukecarbis** [comment]
I also tried with my WP Admin set to Arabic, without problem.

![Screen Shot 2019-03-12 at 3 13 44 pm](https://user-images.githubusercontent.com/1097667/54176192-9599fe00-44d9-11e9-872a-04a01229bcba.png)
![Screen Shot 2019-03-12 at 3 14 10 pm](https://user-images.githubusercontent.com/1097667/54176194-96cb2b00-44d9-11e9-951a-ad451ea65bcb.png)
