### ISSUE TITLE
Block not displayed

### ISSUE THREAD

**Issue by Riverskiy** [getblocklab/block-lab#239]
If you use tag “more”, and try post content with strip teaser `<?php the_content(null, true); ?>` blocks are not displayed

**Comment by lukecarbis** [comment]
Can confirm this error exists on a `single` template, when using `the_content(null, true);` to display post content. Changing to `the_content(null, false)` fixes the problem.

I'll try to figure out why stripping the teaser content removes _all_ blocks from the post.

**Comment by lukecarbis** [comment]
Turns out that this is in fact a core bug, not a Block Lab bug. I've filed a trac ticket, and will create a patch for it shortly. https://core.trac.wordpress.org/ticket/46471
