### ISSUE TITLE
$block_lab_config global

### ISSUE THREAD

**Issue by pcfreak30** [getblocklab/block-lab#240]
This is something that may be seen as a nickpick to some. But while WordPress uses globals everywhere, it is still known as a bad practice.

You have the function block_config() that fetches this. However, my suggestion is to make the config a static variable of that function (or possibly even its own class?). In the end, all changes to the config should go through a function. This will be modern best practices.

Thanks :)

**Comment by lukecarbis** [comment]
I agree that this could be handled better, but I don't think the `$block_lab_config` and `$block_lab_attributes` variables should become parameters of the `Plugin` class – mostly because they're used very temporarily. I'm not sure on a better approach though.

**Comment by pcfreak30** [comment]
I didnt say that they needed to be parameters, just at minimum static varibles inside a function. Crude example.

```
function my_store($value = null){
static $data;

if(null !== $value){
$data = $value;
}

return $data;
}

```

Basically, it should at least be encapsulated, and going farther, be its own class.

Thoughts?

**Comment by lukecarbis** [comment]
Makes sense. Having a `Data` or `Data_Store` class would be the way to go. Seems like overkill just to remove two global variables, but I agree it would be better practice. Unfortunately, I've got to give this one a pretty low priority.

**Comment by lukecarbis** [comment]
Closing this in favour of #425.
