### ISSUE TITLE
Getting an "Error loading block: Invalid parameter(s): context" in editor

### ISSUE THREAD

**Issue by lensco** [getblocklab/block-lab#244]
Just added a new block, and displaying the block contents in the editor shows me an `Error loading block: Invalid parameter(s): context` message when not focused. Input, saving and displaying on the website all work fine.

**Comment by lukecarbis** [comment]
Thanks for reporting @lensco . I've seen this popup in development before, but not on the current version of the plugin. Could you please report back with:
- Your WordPress version
- Your Block Lab version
- Whether or not you're using the Gutenberg plugin
- Your blog config?

**Comment by lensco** [comment]
I'm working on a local (Mac) machine here with Wordpress 5.1 and Block Lab 1.2.0. Using the default block editor, and a mostly vanilla Wordpress install. Anything else you need to know?

**Comment by lukecarbis** [comment]
What fields are in your block? What settings did you use? I'll try to replicate the issue so that I can fix it.

**Comment by lensco** [comment]
Setup is super simple:

<img width="1135" alt="setup" src="https://user-images.githubusercontent.com/246481/53987081-3d9d7900-4120-11e9-9dbf-427e6c15b67f.png">


The block template is this:
```html
<div class="transcript">
	<?php block_field( 'transcripttext' ); ?>
</div>
```

**Comment by lukecarbis** [comment]
@lensco Looking at this again and having trouble replicating the problem. How did you install Block Lab? From the WordPress.org repo, or by downloading it from Github?

**Comment by lensco** [comment]
I'm not 100% sure anymore, but I think I got it from Github and installed manually.

**Comment by lukecarbis** [comment]
That might explain it. When using the sources from Github, you need to manually run `npm install`, then `npm build` before the javascript and css is properly compiled.

**Comment by lensco** [comment]
I have removed the plugin and reinstalled straight from the Wordpress backend, and I'm getting the same error. Is there anything that needs to be reset?

**Comment by lukecarbis** [comment]
When you say the "WordPress backend", what exactly do you mean? Uploading a zip into WordPress won't help.

The best way of installing the plugin is to go to the WP Admin, then Plugins > Add new, search for "Block Lab" in the Plugin repo, and then Activate it.

I'll update the README to reflect this, as currently it's inaccurate.

**Comment by lukecarbis** [comment]
See #248.

**Comment by Artaud** [comment]
I got a very similar issue that I can reproduce reliably.

How to reproduce:
1. Create any block in blocklab (even a super simple block with one text field, that just renders the text)
2. Add the block to a page
3. **Add a custom CSS class to the block** using the Gutenberg block settings menu (Block > Advanced)

2. Result
The block does not render in the editor, and throws "Error loading block: Invalid parameter(s): attributes". The error does not go away when you clear the custom CSS class.
The block does render OK on the frontend.

3. Additional information
- Wordpress 5.1.1
- Latest blocklab installed from wordpress repo

**Comment by lukecarbis** [comment]
@lensco I've just tried rebuilding your block exactly as you have described, and I can't replicate the error. Can you please confirm that you installed Block Lab from the WordPress plugin repo, and not from Github?

@Artaud I was able to replicate this problem, but decided to create a separate ticket to discuss it.

**Comment by lensco** [comment]
Yes, I installed from the Wordpress plugin repo. However, I just tested some more, and I think my issue is simply with the length of the contents of the field? When I shorten the text I paste in the transcript field, it renders just fine in the editor. Are there any limits here?

**Comment by lukecarbis** [comment]
@lensco At 6000 characters I get a "The response is not a valid JSON response" error, which I'm glad we've picked up!

But it's not the error you mentioned.

Perhaps you could drop the content you're trying to use into pastebin.com? It sounds like it might be a specific character.

**Comment by lensco** [comment]
Sure, here it is: https://pastebin.com/9yuS6z4R
It's a bunch of markdown, which I parse in PHP on display. The editor seems to parse it as well (when I shorten it).

**Comment by lukecarbis** [comment]
I also get an error with that. It's a different error, related to word count, though.

Can you experiment to try to find out how much you can fit in the text box before it breaks? My experience has been somewhere between 5,500 and 6,500 characters.

**Comment by lensco** [comment]
I tried a whole bunch of different combinations, and no luck getting consistent numbers. Depending on the content, it fails somewhere between 11,000 and 12,000 characters. Thenk I checked word count and couldn't get anything consistent either. Weird.

**Comment by lukecarbis** [comment]
Closing this in favour of #254.
