### ISSUE TITLE
No access error on "Go Pro" page once license is activated

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#245]
I noticed today that when you activate your Pro license via the "Go Pro" page in the WP Admin, once it's activated you get a "You can't access this page" style error. I think this is because the page disappears once the license is activated, but it doesn't redirect elsewhere and instead tries to reload the page.
A simple solution for this would be to redirect to the Settings page after license activation.

**Comment by lukecarbis** [comment]
@RobStino Can you please double check this? On my install it redirects to the settings page.

**Comment by pcfreak30** [comment]
Hmm got this myself when I activated it.

**Comment by RobStino** [comment]
Testing this again, and I can't replicate the issue.
Note, someone in the Community Slack referenced this issue though. I'll share this with them in case they have further inights.

**Comment by lukecarbis** [comment]
Yeah I've found it hard to replicate too – my hunch is that it only happens on environments with slow-ish / no internet. @RobStino Could you try that?

**Comment by fschmittlein** [comment]
I have the same issue an the same message
