### ISSUE TITLE
Is it possible to use standard image presets when outputting images?

### ISSUE THREAD

**Issue by MattKevan** [getblocklab/block-lab#247]
It would be great use the built-in image presets to display images.

For example an option in the inspector to select an image preset, or to print images in a template using a preset.

Something like ```<?php block_field( 'image_field','image_preset' ); ?>```

**Comment by lukecarbis** [comment]
Could you describe more about what you mean by a preset? What would be the expected output?

**Comment by MattKevan** [comment]
Hi Luke, what I mean is being able to use one of the image presets defined in ```add_image_size()``` in functions.php to output an image.

**Comment by lukecarbis** [comment]
@MattKevan We're currently reworking the way images are returned so that you can get the attachment post ID (#260). Once that's implemented, you can use `wp_get_attachment_image_src()` with the ID to pull down whichever size you like.
