### ISSUE TITLE
Adding custom CSS causes error

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#253]
I got a very similar issue that I can reproduce reliably.

How to reproduce:
1. Create any block in blocklab (even a super simple block with one text field, that just renders the text)
2. Add the block to a page
3. **Add a custom CSS class to the block** using the Gutenberg block settings menu (Block > Advanced)

2. Result
The block does not render in the editor, and throws "Error loading block: Invalid parameter(s): attributes". The error does not go away when you clear the custom CSS class.
The block does render OK on the frontend.

3. Additional information
- Wordpress 5.1.1
- Latest blocklab installed from wordpress repo

_Originally posted by @Artaud in https://github.com/getblocklab/block-lab/issues/244#issuecomment-473246294_

**Comment by kienstra** [comment]
#293 should prevent this error.

**Comment by kienstra** [comment]
This was mentioned on this wp.org support topic. It'd be nice to ping `@eriktdesign` there when the fix is released:

https://wordpress.org/support/topic/adding-classname-to-custom-blocks/#post-11521342

**Comment by eriktdesign** [comment]
Thanks @kienstra -- I'll follow here.
