### ISSUE TITLE
Preview php file is not loaded.

### ISSUE THREAD

**Issue by DieTapete** [getblocklab/block-lab#262]
Seems like this was an issue already and was fixed in 1.1.1. but I still can't get it to work. Could it be that this feature is broken again?

**Comment by lukecarbis** [comment]
Seems to work okay for me. What are you using for the filename, and where are you putting the template?

![2019-03-25 09-12-14 2019-03-25 09_18_39](https://user-images.githubusercontent.com/1097667/54887454-03352980-4edf-11e9-92df-fb806f2a353b.gif)

**Comment by DieTapete** [comment]
Alright, thanks for the video. I used the format `preview-block-[blockname].php` instead of `preview-[blockname].php`. Maybe an example name in the documentation would help other people not to get confused.

**Comment by lukecarbis** [comment]
Glad that got it sorted @DieTapete! The preview format has been added to the wiki here: https://github.com/getblocklab/block-lab/wiki/3.-Displaying-custom-blocks#block-previews
