### ISSUE TITLE
Block only renders comment, not content

### ISSUE THREAD

**Issue by darrenbarklie** [getblocklab/block-lab#263]
Hi Luke,

Using the latest version, I believe my setup is correct, however encounter the same issue in two separate WP environments.

The plugin correctly identifies the block template, however I can't get my post content to render through to the frontend.  The content is pulled through as comments that can be viewed via the console, but none of the HTML is respected.

Appreciate any support/guidance.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3026261/54886107-0f3bcf80-4e7c-11e9-9bcb-9c7f65641258.png">

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/3026261/54886094-eca9b680-4e7b-11e9-8e36-d879803ef110.png">

**Comment by lukecarbis** [comment]
Are other blocks working?

What happens if you remove the comment at the top of your template?

**Comment by darrenbarklie** [comment]
I created a new block with only the minimal code, but as before the content is only pulled as JSON in the comment.

![image](https://user-images.githubusercontent.com/3026261/54901238-c6146b80-4ecd-11e9-81bd-f655546d32cb.png)
![image](https://user-images.githubusercontent.com/3026261/54901344-11c71500-4ece-11e9-8d3a-182fc4d06f2a.png)

**Comment by lukecarbis** [comment]
@darrenbarklie Do you have any javascript errors in your console?

Can you try disabling all other plugins and see if that fixes the problem?

Can you also try switching to a default theme and see if that helps?

**Comment by darrenbarklie** [comment]
@lukecarbis No JS errors.  Reverting to the base theme did cause the content to render correctly:

![image](https://user-images.githubusercontent.com/3026261/54917274-5c0ebd00-4ef3-11e9-9a79-cad5864a418d.png)

My custom theme was based off the Automattic starter theme [Underscores](https://underscores.me/).  Strange that it wouldn't facilitate this.

I'll continue to debugging this with against a fresh installation of Underscores to figure out the fault and report back.

**Comment by darrenbarklie** [comment]
I can confirm that the blocks continue to work with default underscores theme.  Edits to my custom theme must be causing the issue.  Will continue to investigate and close the issue.  Thanks for the prompts @lukecarbis

**Comment by darrenbarklie** [comment]
I discovered I had called `get_the_content();` instead of `the_content();`.
