### ISSUE TITLE
Feature Request: Layout elements (containers) with nesting.

### ISSUE THREAD

**Issue by Tarka-Dhal** [getblocklab/block-lab#271]
Hello, first I have to say you are doing a great job. I really enjoy block lab and hope that it will be a great tool in future! I don't know if you are planning this feature but I didn't find it anywhere (only discussion here: #157). It would be great if you will add layout elements (containers) with nesting. For example: custom columns, containers, etc. - https://i.snag.gy/cmx3Hw.jpg

This feature is really needed! :-)

**Comment by lukecarbis** [comment]
Thanks for raising this @tarka-dhal. We know it’s an important feature for a lot of people! We’re tracking this in #157, so I’ll close this issue out in favour of that one.
