### ISSUE TITLE
User input should store ID as well as username.

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#288]
I noticed that the user field only saves the username, not the ID. This is different to the post field, which stores both (title and ID). The user field should store an array like the post field, for consistency.

Current:
```
<!-- wp:block-lab/post–vs-user
{
    "text-only": "Test",
    "post": {
        "id": 2,
        "title": "Sample Page"
    },
    "user": "lukecarbis"
}
/-->
```

Target:
```
<!-- wp:block-lab/post–vs-user
{
    "text-only": "Test",
    "post": {
        "id": 2,
        "title": "Sample Page"
    },
    "user": {
        "id": 42,
        "name": "lukecarbis",
        "nicename": "Luke Carbis",
    },
}
/-->
```

Potentially we don't need to store the `name` (login name), only the `nicename`, as the `name` is not currently needed.

**Comment by kienstra** [comment]
**Question About Backward Compatibility**

Hi @lukecarbis,
Thanks for opening this issue from #257. 

How important is it to keep backward compatibility? It's going to be a little complex, probably filtering [render_block_data](https://github.com/WordPress/wordpress-develop/blob/98e942e10c53e7edd8075fc3fe68eff289cb2db2/src/wp-includes/blocks.php#L201) for the block rendering. And also converting the values in the `user.js` file.

**Comment by lukecarbis** [comment]
If backwards compatibility is going to be difficult to achieve, I think we can settle for notifying all Pro customers about the change, since the User field is only available to them.

**Comment by kienstra** [comment]
Sounds good. Sorry for the delay on this, would it be alright if I worked on it tomorrow (my Monday)?

**Comment by lukecarbis** [comment]
Of course!
