### ISSUE TITLE
Unable to publish a block with non-english title

### ISSUE THREAD

**Issue by RayPS** [getblocklab/block-lab#295]
Reproduce step: create a block with a Chinese title and publish.

**Comment by lukecarbis** [comment]
I've tried reproducing this as described (actually, in both Hebrew and Chinese), but it's worked every time for me. Could you show me how your block is configured?

![Screen Shot 2019-04-28 at 10 50 42 am](https://user-images.githubusercontent.com/1097667/56856751-86e1aa80-69a4-11e9-8a52-75ed8806acfd.png)

![Screen Shot 2019-04-28 at 10 51 00 am](https://user-images.githubusercontent.com/1097667/56856752-8812d780-69a4-11e9-83b8-c1f472affc57.png)

![ScreenFlow](https://user-images.githubusercontent.com/1097667/56856753-8b0dc800-69a4-11e9-98eb-b55c8ab7c5fb.gif)

**Comment by RayPS** [comment]
This is 100% reproducible here, even with a empty block configuration. The “update” button only responds to a english title. Is there any information I can provide?

**Comment by lukecarbis** [comment]
Yes – can you screenshot the Block (obviously before you publish it)? And maybe copy / paste the text values you're using so I don't have to figure out how to type them myself!

**Comment by RayPS** [comment]
Here is a screen recording of the reproduction:
![Screen Recording 2019-05-05 at 18 59 12 2019-05-05 19_03_56](https://user-images.githubusercontent.com/1941540/57192931-9050b100-6f68-11e9-93b9-5d7706bf5d4d.gif)

**Comment by lukecarbis** [comment]
@RayPS I've followed along with the gif exactly, using WordPress 5.1.1 and Block Lab 1.3.0, however Publishing works perfectly fine for me. I tried in Safari and Chrome on Mac.

Is it possible that there's another plugin that could be causing this? Could you try with only Block Lab enabled and nothing else?

**Comment by RayPS** [comment]
I've tried your suggestion with a fresh wp docker image and the result are certainly like your expect. But so far I have no way to identify with plugin was causing this problem. Thanks so much for figured out.
