### ISSUE TITLE
Images not saving after latest update

### ISSUE THREAD

**Issue by MattKevan** [getblocklab/block-lab#297]
Hi, after upgrading to the latest version of the plugin, I've noticed that images aren't saving. 

After selecting an image, it's displayed in the preview, but it disappears on saving the post. It's not shown on the page, and going back into edit page shows an empty field.

I've attached a quick screen recording to show it in action.

[Screen Recording.mov.zip](https://github.com/getblocklab/block-lab/files/3121693/Screen.Recording.mov.zip)

**Comment by kienstra** [comment]
**Sorry**
*Possible Workaround*

Hi @MattKevan,
Thanks for letting us know about this, and for your nice [screen recording](https://github.com/getblocklab/block-lab/files/3121693/Screen.Recording.mov.zip).

I also see this issue, sorry I missed it before.

As a workaround, could you go to the block with the image in `/wp-admin` > Block Lab, and click "Update"? There's no need to change anything.

![updating-this](https://user-images.githubusercontent.com/4063887/56831936-1ade3580-6830-11e9-9c0c-682a468cfba8.gif)

Could you please let me know if that works? It worked for me locally.

Sorry about this, and have a great Friday.

**Comment by aldenfbrown** [comment]
Hello @kienstra,

Unfortunately this fix did not work for us locally or on our deployed instance living on WP-Engine. Please let us know if you would like us to test any other work around. 

Thanks in advance!
Alden

**Comment by kienstra** [comment]
Hi @aldenfbrown,
Thanks, could you please help with some more details about the issue?

Did you create a block with an image field before [version v1.2.3](https://wordpress.org/plugins/block-lab/#developers) (released on April 23rd), upgrade to `v1.2.3`, and have problems saving new changes to the block?

If it's on a live URL, it'd be great if you could share a link.

Thanks!

**Comment by aldenfbrown** [comment]
@kienstra, 

Thanks for the reply. We are not able to update image fields that are in blocks created before the 1.2.3 release and image fields in new blocks created after the release. After reverting the back to the 1.2.2 release and updating the blocks the image fields are rendering as expected. Unforunately, I can not provide you a link without approval although that may be something I can get. Let me know if that is going to be necessary. 

Thanks again!
Alden

**Comment by kienstra** [comment]
Hi @aldenfbrown,
Thanks for the details. 

>Unfortunately this fix did not work for us locally or on our deployed instance living on WP-Engine. 

It sounds like you took the step shown below for every block with an image field, right?

![updating-this](https://user-images.githubusercontent.com/4063887/56831936-1ade3580-6830-11e9-9c0c-682a468cfba8.gif)

(For every block that has an image, going to /wp-admin > Block Lab, selecting the block, and clicking "Update")

**Comment by aldenfbrown** [comment]
We did, although that did not resolve the issue.

**Comment by kienstra** [comment]
OK, thanks. I'm going to test this again to see if I can reproduce it.

**Comment by aldenfbrown** [comment]
Thank you!

**Comment by kienstra** [comment]
**Sorry, Another Question 😄**

Hi @aldenfbrown,
Thanks for confirming.

It sounds like you're pretty savvy, so sorry to run through this again.

But have you done a "hard refresh" when in the block editor (Shift + Command + R in Mac and Chrome)?

The block attributes are in a JavaScript `const`, and might have been cached.

I couldn't reproduce this. Going from [version 1.2.2](https://plugins.trac.wordpress.org/browser/block-lab?rev=2063297) to [version 1.2.3](https://plugins.trac.wordpress.org/browser/block-lab?rev=2072809) seemed to work fine, as long as I [clicked Update](https://github.com/getblocklab/block-lab/issues/297#issuecomment-488109183) like we talked about.

Steps I took:
1. Deactivate and delete Block Lab
2. `cd` to `wp-content/` directory
3. `svn co https://plugins.svn.wordpress.org/block-lab/ svn-bl`
4. `cd svn-bl && svn update -r 2063297` # plugin version 1.2.2
5. Copied `trunk/` directory to `wp-content/plugins/`
6. Created a new block with an Image field, verified it worked
7. `cd` back to `svn-bl` and then `svn update -r 2072809` # plugin version 1.2.3
8. Removed current `block-lab` plugin, copied `trunk/` directory to `wp-content/plugins/`
9. Clicked "Update" for the block, as [shown in the .gif](https://github.com/getblocklab/block-lab/issues/297#issuecomment-488109183)
10. Went to the block editor, edited the block, and noticed that the new image saves

**Comment by aldenfbrown** [comment]
I will give that a shot and let you know either way. Thanks!

**Comment by kienstra** [comment]
**Testing On Staging?**

Hi @aldenfbrown,
Also, have you tested this on staging? 

Maybe you have a different WP Engine setup than me, but if you could possibly copy the live site to staging, it'd be interesting to see if this still existed:

<img width="665" alt="staging-site" src="https://user-images.githubusercontent.com/4063887/56997146-65cbb600-6b6c-11e9-98f1-bc6aaa912d84.png">

Maybe this is related to the host caching, though that's just a guess.

**Comment by aldenfbrown** [comment]
OK here is what have, it appears the image fields are returning an id vs. url with the update to 1.2.3 and 1.3.0.

**before the update:**
`{
"blockName": "block-lab/large",
"attrs": {
"image-src": "http://localhost:8000/wp-content/uploads/2019/04/arrow-up.png",
}
},`

**after the update:**
`{
"blockName": "block-lab/large",
"attrs": {
"image-src": 653,
}
},`

This happens even after all the steps above in private browsing mode and after clearing the page cache in wp-engine. Clearly, the same result on my local instance as well.

**Comment by kienstra** [comment]
Hi @aldenfbrown,
Thanks a lot for those details.

Both **before the update** and **after the update** the  attributes look right. It's expected that after the update to `1.2.3`, the `"image-src"` [be an integer](https://github.com/getblocklab/block-lab/blob/3dd303328e9f518cc1daa6cbeadbd601289a671d/php/blocks/controls/class-image.php#L29).

1. Is the image not appearing, even though it's saving those attributes? Does it look something like this after you've selected an image:

<img width="916" alt="image-not-appearing-here" src="https://user-images.githubusercontent.com/4063887/57003053-79d1e080-6b89-11e9-8efa-cac52d5d9b49.png">

2. Are your environments running the [Gutenberg plugin](https://github.com/wordPress/gutenberg/) by chance, and what version? Of course it's not necessary, it's bundled in WP Core now.

I'm not sure what could be causing this. It's working locally here. 

Let me keep looking on this, I also might ask some other people on the team here.

**Comment by kienstra** [comment]
**Could you please help?**

Hi @lukecarbis,
Could you please test this? I couldn't reproduce it, but I could have missed something.

It sounds the issue that's reported is:
1. Start with a version before `v1.2.3`, like `v1.2.2`
2. Create a block with an Image field, create a post with the block, select an image for the block, and save
3. Upgrade to version `v1.2.3` or `v1.3.0`
4. Go to the block UI, and click "Update":
![updating-this](https://user-images.githubusercontent.com/4063887/56831936-1ade3580-6830-11e9-9c0c-682a468cfba8.gif)
5. Go to the same block in the block editor
6. Change the image, click "Update," and refresh the page
7. Expected: the saved image appears 
8. Actual: no image appears, maybe like this:
<img width="916" alt="image-not-appearing-here" src="https://user-images.githubusercontent.com/4063887/57003053-79d1e080-6b89-11e9-8efa-cac52d5d9b49.png">


Here are [the steps I took](https://github.com/getblocklab/block-lab/issues/297#issuecomment-488134605), though I couldn't reproduce it.

Thanks, Luke!

**Comment by lukecarbis** [comment]
I was able to reproduce it. My 10 minute walk-through which includes testing a bunch of different ideas is here: http://fromsmash.com/d921ab0c-6f91-11e9-b6fe-06812412be8a

In the end, I found the issue was isolated to:
- Only the image field
- Only fields with a dash in the slug (I used `image-src`)

**Comment by kienstra** [comment]
Thanks, @lukecarbis!

**Comment by kienstra** [comment]
**Question about updating the block**

Hi @lukecarbis,
Thanks a lot for testing this. Your screencast really helped.

Did you do step 4 [above](https://github.com/getblocklab/block-lab/issues/297#issuecomment-488810130) (Go to the block UI and click update)?

It's a little confusing how I wrote that step. "Block UI" refers to the `/wp-admin` > Block Lab > Edit Block UI, not the block editor:

<img width="1433" alt="this-ui-not-the-block-editor" src="https://user-images.githubusercontent.com/4063887/57206925-18e24800-6f8f-11e9-820c-1b73e4a661e2.png">

That step is definitely not ideal. I should have caught it earlier when changing the image control.

But when I took that step, it allowed the image to save and display.

Thanks a lot for testing this, Luke! I've been struggling with reproducing this.

**Comment by lukecarbis** [comment]
@kienstra Ah yes! I didn't do this. Just ran back to my Local Dev environment and tried it, and everything works. You're right, I did get confused by the instruction. I needed to **Update** the Block itself, not the post containing the block.

@aldenfbrown @MattKevan Have you tried this?

**Comment by Artaud** [comment]
@kienstra, sorry for me too, but I have encountered the issue too and just updating the block helped resolve it.

**Comment by kienstra** [comment]
Thanks, @Artaud!
