### ISSUE TITLE
Block Theme Folder Structure

### ISSUE THREAD

**Issue by designmonkeymedia** [getblocklab/block-lab#301]
It would be great and much tidyer if we could structure the blocks in the theme/blocks/ folder for each block e.g.

- /theme
  - /blocks
     - /block_one
         - preview.php
         - block.php
         - block.js
         - block.css
      - /block_two
         - preview.php
         - block.php
         - block.js
         - block.css

This would be great!

Thanks,

Sam

**Comment by kienstra** [comment]
**Thanks For Opening This!**

Hi @designmonkeymedia,
Thanks a lot for suggesting this. It would be easier to be able to structure blocks like this.

We'll consider this. If we plan on adding it to a release, you'll see a milestone added to it, like [1.3](https://github.com/getblocklab/block-lab/milestone/5) or [1.4](https://github.com/getblocklab/block-lab/milestone/6)

**Comment by lukecarbis** [comment]
@RobStino Any thoughts?

**Comment by RobStino** [comment]
Wow. Delayed review from me. :D Sorry about that.
It's an interesting idea. I think I'd have to say I agree.
One site I'm working on at the moment has about 20 custom blocks and more structure like this would make it easier to navigate.
@kienstra @lukecarbis Is there anything technical stopping use form adding this as another templating path that Block Lab can auto-magically navigate and pair files?

**Comment by lukecarbis** [comment]
I think this should be pretty easy.

**Comment by kienstra** [comment]
>Is there anything technical stopping use form adding this as another templating path that Block Lab can auto-magically navigate and pair files?

There's no blocker to this, we could add logic to [block_lab_locate_template()](https://github.com/getblocklab/block-lab/blob/ad4c916b0b31f79be851b43f0d5a79ea73cd6ef9/php/helpers.php#L167).
