### ISSUE TITLE
"Container" control type

### ISSUE THREAD

**Issue by robertsass** [getblocklab/block-lab#305]
It would be awesome to have a simple Container block, that takes other blocks so that you can nest blocks and build individual layouts.
_Lazy Blocks_ calls that "Inner Blocks": https://lazyblocks.com/documentation/blocks-controls/inner-blocks/

**Comment by kienstra** [comment]
**Thanks!**

Hi @robertsass,
Thanks, this is an interesting idea.

We'll consider this. If we plan on adding it to a release, you'll see a milestone added to it, like [1.4](https://github.com/getblocklab/block-lab/milestone/6) or [1.5](https://github.com/getblocklab/block-lab/milestone/7).

**Comment by lukecarbis** [comment]
Closing in favour of https://github.com/getblocklab/block-lab/issues/157.
