### ISSUE TITLE
Import block fields from PHP template

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#316]
It would be really helpful if I could just upload my block template file, e.g. 

```
<div class="text-button"><a href="<?php block_field( 'link-url-1' ); ?>"><?php block_field( 'link-title-1' ); ?></a></div>
<div class="text-button"><a href="<?php block_field( 'link-url-2' ); ?>"><?php block_field( 'link-title-2' ); ?></a></div>
<div class="text-button"><a href="<?php block_field( 'link-url-3' ); ?>"><?php block_field( 'link-title-3' ); ?></a></div>
```

And then Block Lab automatically added the fields from that template file to my block (e.g. link-url-1, link-title-1, etc.).  Would save a lot of manual entry and keep me focused on the front-end.

**Comment by lukecarbis** [comment]
Interesting! Simplifying the process of building blocks has always been top priority for us, but we've always taken a "WP Admin" first approach. I like that you're approaching this from a different angle.

How would Block Lab know what field type each field is? How would know what settings to use for each field? (e.g. help text or default values)

**Comment by x5hwuk7nc6jsudcc** [comment]
The Field Label we know, and you could probably de-slug and capitalise that for the Field Name as a default.

A sensible approach for the Field Type would be to default everything to Text, unless the field exists on a known attribute.  For example, if it exists on a "src" attribute you could default it to Image.  If it exists on an "href" attribute you could default it to URL.

All other fields could keep their current defaults, i.e. Field Location is Editor and the remaining options are blank.  

These will ultimately need tweaking after the import, but it would be a very helpful start.

**Comment by lukecarbis** [comment]
@strayguevara I like the way you're thinking. Technically, this is a really tough ask, and could make the codebase pretty heavy. 

If your main goal is to create a block programatically, maybe you could try building a JSON file manually? You can drop a JSON file in your theme's `blocks` folder, and Block Lab will automatically use that. Here's an example of what it might look like:

```
{
    "block-lab\\/simple-text-block": {
        "name": "simple-text-block",
        "title": "Simple Text Block",
        "icon": "font_download",
        "category": "common",
        "keywords": [
            "keywords",
            "go",
            "here"
        ],
        "fields": {
            "heading": {
                "name": "heading",
                "label": "Heading",
                "control": "text",
                "type": "string",
                "location": "editor",
                "order": 0
            },
            "border-color": {
                "name": "border-color",
                "label": "Border Colour",
                "control": "color",
                "type": "string",
                "location": "inspector",
                "order": 1,
                "help": "Choose a colour for the border.",
                "default": "#FF0000"
            },
            "content": {
                "name": "content",
                "label": "Content",
                "control": "textarea",
                "type": "textarea",
                "location": "editor",
                "order": 2,
                "number_rows": 4,
                "new_lines": "autop"
            }
        }
    }
}
```

**Comment by x5hwuk7nc6jsudcc** [comment]
@lukecarbis the objective is really about reducing the time spent configuring the plugin.  In other work we do, we use static site generators like Jekyll and Hugo a lot. In their respective templating languages you can focus on writing up the front-end of the site and create variables as you go.  What I really like about your plugin is that it creates a similar environment for WordPress where we can just focus on creating awesome templates, and allow the user to configure variables later.  That's really exciting.

The problem is that in creating lots of variables, we then need to go in and create all of the configuration for them in the admin back-end.  If this could be automated, it would save a huge amount of time.

I understand we can create a JSON file for the blocks, which would be slightly faster than doing it via the WordPress dashboard.

If an import tool is going to bloat your plugin, what about a tool that gets us started on a JSON file by grabbing the fields in the PHP template and converting them into a JSON array?

**Comment by lukecarbis** [comment]
When you put it like that, I can see how an "import from template" plugin could be really useful – even if it's not intelligently guessing input types (everything just defaults to `text`).

If it were an add-on, instead of in the main plugin, that would solve a lot of my concerns around code bloat.

**Comment by lukecarbis** [comment]
@strayguevara I'm going to close this in favour of #326, as I think that addresses the problem you describe really neatly.
