### ISSUE TITLE
Block Icon is off-centre

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#319]
Noticed today that the block icon is off-centre when the block is selected in the editor.
A GB core update must have nudged the padding a bit or something.

![image](https://user-images.githubusercontent.com/1578148/58442235-992e4000-812c-11e9-9a06-6c32396e085b.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
This does appear to be coming from WP core (see screenshot attached).  It is also affecting icons from default WP blocks (see for example "widgets/latest posts").

Give that it's coming from WP core and is affecting default blocks, not sure if you intend to fix it.  If you do, this css will do it:
```
.components-icon-button.has-text svg {
  margin-right: unset;
}
```
![inspector](https://user-images.githubusercontent.com/19599955/58604351-62e0f400-82d7-11e9-95d6-debafba57a09.png)

**Comment by lukecarbis** [comment]
I agree with @strayguevara – let's leave this for a core fix.
