### ISSUE TITLE
Unregister core/default Gutenberg blocks

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#322]
It would be useful to be able to unregister core Gutenberg blocks with a simple check/uncheck functionality.

For example, we have written our own Heading block, and so the default Heading block is superfluous.  This may lead to confusion for end-users, and so having the ability to unregister easily would be helpful.

**Comment by lukecarbis** [comment]
I feel that this is a little out of scope for Block Lab. Plus, WordPress core already has a Block Manager:

![2019-05-29 14-56-33 2019-05-29 14_57_18](https://user-images.githubusercontent.com/1097667/58530436-14255280-8222-11e9-8a7f-760625a054a2.gif)
