### ISSUE TITLE
Update documentation for Post field type

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#323]
This is a great plugin and you're all doing an awesome job!

Documentation needs to be added for using the Post field type here: https://github.com/getblocklab/block-lab/wiki/6.-Available-field-types

There is a little explanation on how to use them here: https://github.com/getblocklab/block-lab/pull/257#issuecomment-484757502

Keep up the good work!

**Comment by x5hwuk7nc6jsudcc** [comment]
I'm also happy to help contribute to documentation if required

**Comment by lukecarbis** [comment]
This is on my radar, but if you'd like to help out, that would be amazing!

**Comment by x5hwuk7nc6jsudcc** [comment]
Happy to contribute to documentation. Useful for our own reference anyway. Just tell me how.

**Comment by lukecarbis** [comment]
You should be able to add and edit pages here: https://github.com/getblocklab/block-lab/wiki – let me know if there's some sort of access restriction.

**Comment by x5hwuk7nc6jsudcc** [comment]
I don't see an option to add or edit..
![Screen Shot 2019-05-30 at 13 49 01-fullpage](https://user-images.githubusercontent.com/19599955/58607157-cff98700-82e1-11e9-93b7-42479769a748.png)

**Comment by x5hwuk7nc6jsudcc** [comment]
Thanks, that works now.

**Comment by lukecarbis** [comment]
Just changed something – can you check again?

**Comment by x5hwuk7nc6jsudcc** [comment]
Looks good.

**Comment by x5hwuk7nc6jsudcc** [comment]
Let me know if you're happy with these: 

Posts - https://github.com/getblocklab/block-lab/wiki/6.-Available-field-types#post
Taxonomy - https://github.com/getblocklab/block-lab/wiki/6.-Available-field-types#taxonomy

**Comment by lukecarbis** [comment]
@strayguevara Looks great! I made a couple minor tweaks. Thank you!
