### ISSUE TITLE
Show 'category' in Content Block manager admin screen

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#324]
Would be helpful to see the Category in the Content Block manager screen.  Even better if this field was sortable.  

Very crude mock-up attached.
![mock-up](https://user-images.githubusercontent.com/19599955/58604126-9c652f80-82d6-11e9-862d-02c9ed8ffff4.png)

**Comment by lukecarbis** [comment]
Great idea!
