### ISSUE TITLE
Import / Enable / Disable / Register using PHP API

### ISSUE THREAD

**Issue by Tarka-Dhal** [getblocklab/block-lab#326]
**Something like this:**
https://www.advancedcustomfields.com/resources/register-fields-via-php/

**Comment by lukecarbis** [comment]
Great idea for registering new custom blocks with a PHP API.

In terms of enabling / disabling blocks – we're leaving that task to WordPress Core, which already includes a Block Manager.

**Comment by lukecarbis** [comment]
Closing this in favour of #400.
