### ISSUE TITLE
Add support for custom taxonomy

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#330]
The taxonomy control type is excellent. It would be great if this could also accept custom taxonomy, for example the 'product category' and 'product tag' taxonomies that are installed with WooCommerce https://docs.woocommerce.com/document/installed-taxonomies-post-types/

**Comment by lukecarbis** [comment]
@strayguevara We built the taxonomy dropdown to filter out custom taxonomies which don't show in the REST API. This must exclude Product Categories and Product Tags from WooCommerce.

@kienstra Could you explain the reason why we did this? https://github.com/getblocklab/block-lab/blob/develop/php/blocks/controls/class-taxonomy.php#L91

**Comment by kienstra** [comment]
Hi @lukecarbis,
Sure, as I remember, this excludes taxonomies where `show_in_rest'` isn't `true` because they won't appear in the control in the block editor. The block editor uses the REST API to get the taxonomies.

**Comment by lukecarbis** [comment]
Oh course! That makes sense.

I guess this causes an incompatibility with some plugins that are hiding their taxonomies from the REST API. See [`woocommerce/class-wc-post-types.php`](https://github.com/woocommerce/woocommerce/blob/180a0aaf8d9f26f022040185e461e7a90b2f2038/includes/class-wc-post-types.php#L82). The `show_in_rest` argument defaults to `false`.

@strayguevara Could you try adding the following code to your `functions.php` file to see if it forces WooCommerce's Product Category taxonomy to show?

```PHP
add_filter( 'woocommerce_taxonomy_args_product_cat', 'my_theme_force_tax_to_show_in_rest' );

function my_theme_force_tax_to_show_in_rest( $args ) {
    $args['show_in_rest'] = true;
    return $args;
}
```

**Comment by x5hwuk7nc6jsudcc** [comment]
Thanks, @lukecarbis this works:


```
add_filter( 'woocommerce_taxonomy_args_product_cat', 'my_theme_force_tax_to_show_in_rest' );

function my_theme_force_tax_to_show_in_rest( $args ) {
    $args['show_in_rest'] = true;
    return $args;
}
```
