### ISSUE TITLE
block_value returns only the ID instead of the full URL for "image" block types

### ISSUE THREAD

**Issue by abillahbd** [getblocklab/block-lab#331]
How to replicate:

- Create a block and set an "image" field
- Use it in a document and upload an image to the block
- `echo` the value of block_value( 'field-name' ), it returns only the ID instead of the full URL

Expected functionality:
I am new to this project. Tried to find why this happens in the Docs, or if it is intended, but could not. What I understand, is that it should return the full URL of the attachment, instead of the ID.

Thanks anyway for this awesome project.

**Comment by x5hwuk7nc6jsudcc** [comment]
See here: https://github.com/getblocklab/block-lab/wiki/6.-Available-field-types#image

Using `block_field('field-name')` will return the URL, whereas using `block_value('field-name')` will return the Attachment ID.  This allows you to return different image sizes, among other things.  e.g. 

`<?php
$attachment_id = block_value( 'field-name' );
echo wp_get_attachment_image( $attachment_id, 'medium' );
?>`

**Comment by lukecarbis** [comment]
Thanks for your answer @strayguevara. I've added this question to the FAQ on the Wiki, since I've seen it come up a few times now.

https://github.com/getblocklab/block-lab/wiki/7.-FAQ
