### ISSUE TITLE
Feature Request: a templating function to return all data of a block

### ISSUE THREAD

**Issue by abillahbd** [getblocklab/block-lab#332]
Imaging in one instance of a block in a document, I have the following data:
`"author" => "Neil",
"price" => "30",
"currency" => "USD"`
etc.

I need a function that would return all data of the current instance of the block, so that I can check and process the data from within a helper function somewhere in the `functions.php` file like so:

`if ( $author == 'Neil' ) {
    echo "Oh! This is Neil!";
}`

Thank you.

**Comment by lukecarbis** [comment]
@abillahbd You can already achieve this in a couple of ways. Your example has an easy solution. Try using the [`block_value()`](https://github.com/getblocklab/block-lab/wiki/4.-Templating-functions#block_value) function.

```PHP
$author = block_value( 'author' );
if ( 'Neil' === $author ) {
    echo "Oh! This is $author!";
}
```

Additionally, you can retrieve all other block settings using the [`block_config()`](https://github.com/getblocklab/block-lab/wiki/4.-Templating-functions#block_config) and [`block_field_config()`](https://github.com/getblocklab/block-lab/wiki/4.-Templating-functions#block_field_config) functions.

**Comment by abillahbd** [comment]
@lukecarbis Unfortunately your example code is not what I meant. The way you did it, it means I have to keep using the same code over and over again in my block's source code. To add to that, imagine if I need to use the same code over multiple blocks, it won't be very nice to use the same code over and over again. On top of that, if I need to change something, that'd be a nightmare.

What I wanted to do instead, is to have a helper function in the themes `functions.php` file, and use it like so:
`echo process_block_data( get_all_block_data() );`
and in the helper function:
`function process_block_data( $data = array() ) {
    if ( $data['author'] == 'John' ) {
        return "Oh! It's John there! How's it going John?";
    }
}`

I hope you get my point.

Thanks!

**Comment by lukecarbis** [comment]
@abillahbd I'm not sure I do get your point. Perhaps you could provide a more practical example?

**Comment by abillahbd** [comment]
@lukecarbis Here's a very practical example, one that I am currently faced with:
Let's say `my_custom_block` has 3 `text` fields, namely, `first_name`, `last_name`, and `display_option`.

One instance of the block in a document has the following data:
`"first_name" => "John", "last_name" => "Doe", "display_option" => "last_"`
Another instance of the same block has this data:
`"first_name" => "John", "last_name" => "Doe", "display_option" => "first_"` (notice the difference in `display_option`)

If I want to show either the first or last name depending on what the user chooses, I have to do this in `my_custom_block.php`:
`if (block_value('display_option')=='first_') { block_field( 'first_name' ) } else { block_field( 'last_name' ) } `

If I need to show this multiple times in the block's output, I have to use the same code over and over again throughout the block's template file. Then imagine if I need to change the `if/else` logic, I have to basically go and change it everywhere.

Wouldn't it be nice if I could do this in `my_custom_block.php`:
`echo show_appropriate_name_part( get_all_data() );`

Then in theme's `functions.php`:
`function show_appropriate_name_part( $block_data = array() ) {
    if ( $block_data['display_option'] == 'first_' ) { return $block_data['first_name']; }
    else { return $block_data[ 'last_name' ]; }
}`

This means, I don't have to hardcode all the data fields in my block's template file. This way, if I want to change anything (of `if/else` etc.), all I have to do is to change it in the function in the `functions.php` file.

I hope you understand now.

Thanks!

**Comment by rheinardkorf** [comment]
@abillabd I think the same can be achieved using a utility function. First parameter is the block and perhaps 2nd and 3rd could be callback functions. 

Even if there was a convenience function in the plugin you would still need to create your own logic methods.

**Comment by lukecarbis** [comment]
@abillahbd Maybe I don't understand? In your block's template file, why not doing something like this?

```HTML+PHP
<?php
$first_name   = block_value( 'first_name' );
$last_name    = block_value( 'last_name' );
$display_name = $first_name;

if ( 'last_' === block_value( 'display_option' ) ) {
    $display_name = $last_name;
}
?>
<h1>
<?php
echo esc_html(
    sprintf(
        __( 'Hello, %s', 'my-theme' ),
        $display_name
    )
);
?>
</h1>
```

You can use `$display_name` as many times as you like in the template. It will display the first or last name depending on the `display_option` selected for each instance of the block.
