### ISSUE TITLE
Child theme block CSS isn't loaded when there's a block CSS file in the parent 

### ISSUE THREAD

**Issue by kienstra** [getblocklab/block-lab#334]
Thanks to @RobStino for finding this.

Steps to reproduce:
1. Create a block, like 'Test Image,' with some control like an Image control
2. Create a template for it in a child theme, like `blocks/block-test-image.php`
3. Create a CSS file for it in the child theme, like `blocks/block-test-image.css`
4. Go to the front-end, and observe that the CSS file is present, as expected:

<img width="798" alt="child-theme-loaded" src="https://user-images.githubusercontent.com/4063887/59234199-408d8700-8bb1-11e9-950a-bfcd6eefb809.png">

5. Add a CSS file of the same name to the parent theme, like `<parent-theme>/blocks/block-test-image.css`

6. Go to the front-end

7. Expected: the child theme stylesheet should be present

8. Actual: only the parent theme stylesheet is present:

<img width="794" alt="parent-theme-stylesheet" src="https://user-images.githubusercontent.com/4063887/59234172-25bb1280-8bb1-11e9-8e61-ec82548301aa.png">

**Comment by kienstra** [comment]
@lukecarbis also found that the template file from the parent theme is overriding the template from the child theme.

**Comment by kienstra** [comment]
**Question About Expected Behavior**

Hi @lukecarbis,
Hope you're having a great day so far.

If there are CSS files for a block in both the parent and the child theme, what should happen?

Like:
`<parent-theme>/blocks/block-test-image.css`
`<child-theme>/blocks/block-test-image.css`

Should this enqueue only the child theme styling, or both?

It looks like `block_lab_locate_template()` is [returning the stylesheet path (parent theme)](https://github.com/getblocklab/block-lab/blob/c7bce5f2e29e786d4e832192c7cde8e265fd9a0d/php/helpers.php#L186) first, and not the child theme (`$template_path`). 

Then, `enqueue_block_styles()` [uses that value](https://github.com/getblocklab/block-lab/blob/c7bce5f2e29e786d4e832192c7cde8e265fd9a0d/php/blocks/class-loader.php#L280) to enqueue the styles.

Thanks, Luke!

**Comment by lukecarbis** [comment]
My day is all the better for having you in it. 😄 

That's a great question. I'm inclined to override the CSS, as that's the same behaviour as WordPress core.

A better question would be what to do in this case:
`<parent-theme>/blocks/block-test-image.css`
`<child-theme>/blocks/css/block-test-image.css`

In this case, I would choose whatever is less complex to implement, as it's extremely edge-case.

**Comment by kienstra** [comment]
Hi @lukecarbis,
Aw, thanks 😄 

It looks like if there's a PHP template for a block in both the parent theme and child theme, it'll use the one in the parent theme.

So it might be a little strange to use the child theme's CSS, while using the parent theme's PHP template.

But you make a good point that using the child theme's CSS instead of the parent theme's is consistent with how Core works.

Do you think we should change the template priority so that it uses the child theme templates over the parent theme? And then change the CSS behavior so it also prioritizes the child theme?

It looks like [block_lab_locate_template()](https://github.com/getblocklab/block-lab/blob/c7bce5f2e29e786d4e832192c7cde8e265fd9a0d/php/helpers.php#L186) returns the parent theme template, not the child theme (though it returns both if the `$single` argument is `true`).

**Comment by lukecarbis** [comment]
@kienstra I'd suggest we should always default to child (template and css) if it exists, and fallback to parent if it doesn't (matching core).
