### ISSUE TITLE
"Internal Link" control type

### ISSUE THREAD

**Issue by adrianbw** [getblocklab/block-lab#338]
I'd really like to see a control that pulled up Wordpress's page selection tool, so I can make a block link to another internal page more easily than hunting down the URL and pasting it in (and then hoping it doesn't change).

**Comment by kienstra** [comment]
Hi @adrianbw, there is a [post control](https://github.com/getblocklab/block-lab/blob/8509d8ced2a678c0ddd1ff8acfa6516ec40c355e/php/blocks/controls/class-post.php) that can search for pages. Unfortunately, it's normally only available with the Pro license. Though you're free to test it from this repo.

For reference, here's [the PR](https://github.com/getblocklab/block-lab/pull/257).
