### ISSUE TITLE
Post control for products only showing 5 products, search filter not working

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#344]
Post control for WC products is only showing the first 5 products.  Scrolling is not working.  Filtering/searching is not working. See video attached.
![recording](https://user-images.githubusercontent.com/19599955/59649762-164a5380-91c7-11e9-9edd-ec060982ac7e.gif)

**Comment by x5hwuk7nc6jsudcc** [comment]
I know you guys are working hard to get 1.4 released but would be great to have a fix for this bug asap :S

**Comment by lukecarbis** [comment]
Absolutely!

**Comment by lukecarbis** [comment]
@strayguevara – I've been messing this for a while this morning, and I was having trouble replicating it.

![2019-07-22 11-02-37 2019-07-22 11_10_23](https://user-images.githubusercontent.com/1097667/61599980-5b075580-ac71-11e9-9037-8ffaeadfbeb9.gif)

Then I had a bit of an idea… I realised that search is probably including the content as well as the title.

I tried it out by adding the text "One" to my product "Product Two". 

![2019-07-22 11-12-01 2019-07-22 11_13_04](https://user-images.githubusercontent.com/1097667/61600029-b76a7500-ac71-11e9-8d88-04ab29ba6044.gif)

Do you think this might be what's causing search to seem like it's not working for you?

**Comment by x5hwuk7nc6jsudcc** [comment]
Ahh! Yes, that's definitely what's going on..
