### ISSUE TITLE
Is it possible to use shortcode to call a block?

### ISSUE THREAD

**Issue by ronniegchagas** [getblocklab/block-lab#347]
Hello everyone!

Is it possible to use shortcode to call a specific block?

If so, how can I call it?

**Comment by ronalfy** [comment]
After looking at the code, it doesn't appear to have a shortcode but instead a helper function called `block_field` which will output the value of the block field. It's easy enough to code a shortcode with attributes that call this function, but from the looks of the code, there isn't shortcode capability.

**Comment by lukecarbis** [comment]
@ronniegchagas I use shortcodes with block lab by creating a text field in my block (let’s give it the name `shortcode`), and then using the `do_shortcode` function:

```PHP
<?php
$shortcode = block_value( 'shortcode' );
do_shortcode( $shortcode );
```
