### ISSUE TITLE
Your site doesn’t include support for the block. You can leave this block intact or remove it entirely.

### ISSUE THREAD

**Issue by rog** [getblocklab/block-lab#352]
I updated the plugin and I got the message:

> Your site doesn’t include support for the block. You can leave this block intact or remove it entirely.

<img width="630" alt="Untitled" src="https://user-images.githubusercontent.com/1069532/60073912-4f168b00-96e7-11e9-8114-d4856b9c33d8.png">

And when I try to edit the block, I don't get the FieldTypes list:
<img width="716" alt="Untitled 2" src="https://user-images.githubusercontent.com/1069532/60073914-4faf2180-96e7-11e9-9931-20c7f48c297d.png">

I can't see any changelog break info about this. What is wrong with my installation?
Also can you use tags between release version? this way we can rollback to past versions.

In the admin editor I got the following error:
![image](https://user-images.githubusercontent.com/1069532/60075467-fd6fff80-96ea-11e9-934b-e428ea1f2a52.png)

**Comment by lukecarbis** [comment]
Hey @rog – I just tried to replicate the error myself, and couldn't manage to cause it. Can you describe how the block was setup, which fields it had, etc?

Also, is the installation registered as Pro?

**Comment by rog** [comment]
No it's no PRO.

I think the problem it's with the `wp.blockEditor` instance, blockEditor is marked as undefined.
Doing some research it's on this line: https://github.com/getblocklab/block-lab/blob/255a41696923f1319e9bdbf0701aefa902836977/js/blocks/controls/rich-text.js#L2

My WP version it's: WordPress 5.1.1

**Comment by paddykontschak** [comment]
@rog you need Wordpress 5.2.2 for BlockLab 1.3.3.
