### ISSUE TITLE
Global blocks

### ISSUE THREAD

**Issue by x5hwuk7nc6jsudcc** [getblocklab/block-lab#354]
This is a feature request.

**Proposed functionality**
Global blocks are like normal blocks, except that when a user edits the content of that block, it updates all instances of that block throughout the site.

**Example use case**
You have a block for your brand USP, which is present on most pages. The intention is for that brand messaging to be the same across all pages, but you also want to allow your end-users to modify that text in the future.

Currently, it is not possible to achieve both objectives and you can either (1) hard code the content inside the block.php so that it forces consistency across all pages or (2) allow the block content to be edited but risk having inconsistencies between pages.

The ability to make this block 'global' would overcome the problem since it would allow content editors to retain control over the content, while reducing the risk and additional work involved in updating each page individually.

**Comment by lukecarbis** [comment]
Interesting idea. 

One workaround that comes to mind that could make this possible now is to create a custom post type – we could call it "Reusable Content", and each post there could contain the content you want to make globally available.

Then create a Block Lab block with a Post selector, set to the Reusable Content post type.

That's not perfectly what you're asking for, but it could be a workaround.

**Comment by lukecarbis** [comment]
@strayguevara On closer inspection, I think this is _exactly_ what Reusable Blocks do. Take a look:

![2019-07-22 20-26-52 2019-07-22 20_29_40](https://user-images.githubusercontent.com/1097667/61626024-79943d80-acbf-11e9-8984-91e0cf7f4816.gif)

**Comment by x5hwuk7nc6jsudcc** [comment]
Amazing! Did not know this feature existed in WordPress.
