### ISSUE TITLE
"Repeater" control type

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#36]
😮

**Comment by AdsonCicilioti** [comment]
Please!

**Comment by AlessandroFerrariFood** [comment]
I think this is the main missing piece.
Please!

**Comment by lukecarbis** [comment]
Couldn't agree more. It's very high priority.

**Comment by AdsonCicilioti** [comment]
![65cd775ce3efaaaf54cfaf0098f1b8cb_256](https://user-images.githubusercontent.com/6278398/54245278-f8f25300-450e-11e9-969f-b790fe11e123.png)

**Comment by danielpickett** [comment]
Yes! Very high priority. This is the only reason I won't use BlockLab for my current task: a logo slider where I would need the user to be able to add any given number of images to the block.

**Comment by pcfreak30** [comment]
My thoughts on the repeaters are storing the data as props on the block as a large JSON blob (inside the blocks HTML comment), and not as meta or options, but that may not be practical? Regardless it should not spam the database, or be DB heavy. That is what I have seen from existing options.
