### ISSUE TITLE
Best practice for relative URLs

### ISSUE THREAD

**Issue by HongPong** [getblocklab/block-lab#367]
Hi all,

Block Lab has been very helpful. I have a question about managing a field that might involve both external and relative URLs. When I try to save a relative URL it rejects that with the validator ("Please enter a URL").

I didn't know until now that HTML inputs of type 'url' forbid relative URLs. sigh! ( https://stackoverflow.com/questions/3670437/input-type-url-for-relative-urls -- also, ACF: https://github.com/AdvancedCustomFields/acf/issues/20 ) 

Is it best to just use a text field instead of the URL field for internal + external use cases?

I would suggest changing either the documentation to note this, or modifying the input widget to a text widget and replacing its validator with something that tolerates both internal and external urls. It would be good to give a suggestion for best management of relative + absolute URL fields.

**Comment by lukecarbis** [comment]
Hey @HongPong – glad you're enjoying Block Lab.

I think we're going to try to stick to the HTML spec when it comes to the URL fields. Unfortunately, that means relative URLs won't work with the URL field.

For now, a standard text field will be best, however, you might like to follow #158 – the Field Validation feature. Once implemented, this will add the ability to add a Regex (or similar) validation, so you could craft a validation method that accepts both relative and absolute URLs.
