### ISSUE TITLE
"Template functions" links to a page that doesn't exist

### ISSUE THREAD

**Issue by bbertucc** [getblocklab/block-lab#368]
After creating a block for the first time, I noticed the "Template Functions" link goes to a page on github that doesn't exist. 

This is the URL it sends you to: https://github.com/getblocklab/block-lab/wiki/4.-Template-Functions

Probably should be this URL: https://github.com/getblocklab/block-lab/wiki/4.-Templating-functions

(note the lowercase "f" in "functions")
<img width="573" alt="Screen Shot 2019-07-15 at 3 50 47 PM" src="https://user-images.githubusercontent.com/46652/61248390-986f5e80-a718-11e9-8c3a-06b30ab9d357.png">

**Comment by lukecarbis** [comment]
Thanks for reporting this! Fixed now.
