### ISSUE TITLE
Handle extra attributes to blocks added via Block API - without errors in the editor

### ISSUE THREAD

**Issue by knutsp** [getblocklab/block-lab#375]
From https://wordpress.org/support/topic/causing-other-blocks-to-not-load-in-editor/#post-11780925

> 2. We add a few attributes to core blocks that extend their capabilities. We use WordPress’ APIs which work just fine with all tested blocks.
> 
> 3. Seems like Block Labs plugin isn’t able to handle the attributes which aren’t pre-defined and don’t accept new attributes added via Block API. In which case it’s an issue with Block Lab and they should fix it.

**Comment by kienstra** [comment]
Hi @knutsp,
Thanks for bringing this up.

If it's alright, we'll carry this conversation forward in the [Otter plugin's support topic](https://wordpress.org/support/topic/causing-other-blocks-to-not-load-in-editor/#post-11787358).

It looks like this issue also appears when using [Otter Blocks](https://wordpress.org/plugins/otter-blocks/) with Core dynamic blocks that use `<ServerSideRender>`. So I'm not sure this is an issue with Block Lab.

<ul>
<li><a href="https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/block-library/src/tag-cloud/edit.js">Tag Cloud</a></li>
<li><a href="https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/block-library/src/archives/edit.js">Archives</a></li>
<li><a href="https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/block-library/src/calendar/edit.js">Calendar</a></li>
<li><a href="https://github.com/WordPress/gutenberg/blob/467e45f787f93d35030ce266a500c627db0e18e5/packages/block-library/src/latest-comments/edit.js">Latest Comments</a></li>
</ul>

<img width="1294" alt="archives-block" src="https://user-images.githubusercontent.com/4063887/62250605-efc92c00-b3b2-11e9-987c-51235dd395ca.png">

**Comment by kienstra** [comment]
**Closing**

Hi @knutsp,
Thanks for raising this. If after further conversation on [Otter's plugin's support topic](https://wordpress.org/support/topic/causing-other-blocks-to-not-load-in-editor/#post-11787358) we find that this is an issue with Block Lab, I'll reopen this.
