### ISSUE TITLE
Allow add_action in block template

### ISSUE THREAD

**Issue by rdcorp** [getblocklab/block-lab#388]
#MyFirstIssue

I tried calling WordPress function 

`add_action("wp_head",function(){});`

in one of the template php files.

But its not working.

However, _do_shortcode_ is working fine.

**Comment by kienstra** [comment]
Hi @rdcorp,
Thanks for brining this up, and for opening your first issue 😄 

It looks like on the front-end (not in the block editor), the `'wp_head'` action will have already run by the time the template runs. 

<img width="974" alt="temp-bl" src="https://user-images.githubusercontent.com/4063887/63264731-236ee600-c2cf-11e9-8883-c522d02b2406.png">

Could you please elaborate on the use case of adding an action to `'wp_head'` inside a template? It's not too typical to add actions inside a template, but maybe there's a compelling reason.

Thanks, Rohan!

**Comment by rdcorp** [comment]
Thanks @kienstra for such a quick reply!

I am creating a FAQ block similar to this one : 

<img width="342" alt="preview-full-authority hacker FAQs desktop" src="https://user-images.githubusercontent.com/4024605/63265058-4509a680-c2aa-11e9-9dc4-82638c0c9d55.png">

I am building Google rich snippet schema from the block template and trying to add it to the header code.

https://developers.google.com/search/docs/data-types/faqpage

**Comment by kienstra** [comment]
Hi @rdcorp,
Thanks a lot for the details.

It looks like it [might be possible](https://codelabs.developers.google.com/codelabs/structured-data/index.html#2) to add structured data in the `<body>`, which is where the template would typically be output:

>JSON-LD should be inside a <script> element in either the `<head>` or `<body>` of the page.

Would that work for your case?

**Comment by rdcorp** [comment]
Sounds good!

I will try it out and update here.

Thanks again!

**Comment by kienstra** [comment]
Thanks, @rdcorp!
