### ISSUE TITLE
Error When using block

### ISSUE THREAD

**Issue by Joshua-Madrid** [getblocklab/block-lab#390]
So I am running into this issue where My block is "Updating Failed" when trying to preview the Results of a POST in wordpress. On the Backend in admin I see the "message Error Loading Block:" and the Preview is stuck in generating. 

here is my folder structure 

**theme>blocks>tshirt-sales>block.php and block.css**

here is the block code used

```
<div id="<?php block_field( 'custom-id' ); ?>" class="card-blocks container-fluid">
    <div class="row">
        <div class="col-md-4"> 
            <div class="card">
            <img class="card-img-top" src="<?php block_field( 'image' ); ?>" alt="">
                <?php
                    $redTag = '';
                    if ( block_value( 'new' ) ) {
                        echo $redTag .= 'NEW!';
                    } elseif ( block_value( 'best-seller' ) ) {
                        echo $redTag .= 'BEST SELLER!';
                    } 
                ?>
                <div class="card-body">
                    <p class="RedTag"><?php echo $redTag; ?></p>
                    <h4 class="card-title"><?php block_field( 'product-name' ); ?></h4>
                    <p class="card-text">
                        <?php
                            $redTag = '';
                            if ( block_value( 'made-in-usa' ) ) {
                                echo $redUSA .= 'USA Made';
                            }
                        ?>
                        <span style="color: red"><?php echo $redUSA; ?></span>
                        <?php block_field( 'short-description' ); ?></p>
                        <img class="card-img-bottom" src="<?php block_field( 'colors-image' ); ?>" alt="">
                    <a href="<?php block_field( 'btn-link' ); ?>" class="btn"><?php block_field( 'btn-text' ); ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
```

this has happened to me 2 times now I am not sure what the issues are.

**Comment by kienstra** [comment]
Hi @Joshua-Madrid,
Thanks for your detailed information.

Are there any other block-related plugins active, other than [Gutenberg](https://github.com/wordPress/gutenberg/)?

There was an issue where when other plugins add other `props`, it can cause a similar error to the one you mentioned: https://github.com/getblocklab/block-lab/issues/375#issuecomment-517034901

After recreating the fields, and using the exact [template above](https://github.com/getblocklab/block-lab/issues/390#issue-483643170), the block displayed fine in my browser:

![template-displays-here](https://user-images.githubusercontent.com/4063887/63476812-d0ab4f00-c4c5-11e9-93b4-764bfe788e8d.gif)

As an aside, in the  [template above](https://github.com/getblocklab/block-lab/issues/390#issue-483643170), it looks like the initial value of `$redUSA` is never assigned. It's only concatenated with a string:

```php
echo $redUSA .= 'USA Made';
```

Maybe something like this would help, before that line above:

```php
$redUSA = '';
```

But even that didn't cause an error locally. It's probably not responsible for this error.

**Comment by Joshua-Madrid** [comment]
I thought it could be a woocommerce blocks so I deleted that plugin since I was not using it but other than that I do not have any other block related plugin active.

**Comment by kienstra** [comment]
Ah, interesting. Thanks for checking that.

Are there any console errors after the message 'Error Loading Block' appears?

**Comment by Joshua-Madrid** [comment]
I am not sure how to see PHP errors in the console I can see Javascript errors sometimes. but nothing for this error. here is a list of the plugins i am using

**Comment by Joshua-Madrid** [comment]
Akismet Anti-Spam
Block Lab
Customizer Export/Import
EWWW Image Optimizer
Google Analytics Dashboard for WP
Premmerce User Roles
Relevanssi
Simple Custom CSS and JS
Sucuri Security
Super Forms 
WC Custom Add to Cart 
WooCommerce
WooCommerce Dynamic Pricing
WooCommerce Min/Max 
WooCommerce Product CSV Import
WooCommerce Services
Yoast SEO

**Comment by Joshua-Madrid** [comment]
Ill email you a video with the issue

**Comment by kienstra** [comment]
Thanks for the information. A video of the issue would help 😄

**Comment by Joshua-Madrid** [comment]
I have block lab pro and can import and export blocks, I am thinking if wipe block lab out and reinstall it, it may work again. or it could be that the database has some other kinda block plugin information remaining?

**Comment by kienstra** [comment]
Hi @Joshua-Madrid,
Sorry for the delay. 

Like you mentioned, saving the block again could help. Simply clicking 'Update' might help:

<img width="1127" alt="click-here" src="https://user-images.githubusercontent.com/4063887/63730248-d4681880-c8ad-11e9-9f5d-265546e6d5c9.png">

Could you please let me know if that works? If not, simply recreating the block from scratch could help.
