### ISSUE TITLE
Blank repeater rows don't show at all

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#393]
If a repeater contains a blank row, we would expect it to be output with default values. However, it currently is not even looped through at all.

**Comment by kienstra** [comment]
This seems to only be a problem in the editor, and it looks to be related to how [ServerSideRender](https://github.com/WordPress/gutenberg/blob/e2490612decf2f0ac614d6ee9f6d1269d0bfc615/packages/server-side-render/src/server-side-render.js#L22) handles empty values.

On the front-end it looks like empty rows display fine.

The issue in the editor seems to be from how `<ServerSideRender>` handles empty objects.

With attributes like:

```json
{
        "example-repeater-field": { "rows": [ {}, {} ] }
}
```
...when `ServerSideRender` [creates the API request string](https://github.com/WordPress/gutenberg/blob/e2490612decf2f0ac614d6ee9f6d1269d0bfc615/packages/server-side-render/src/server-side-render.js#L22), it doesn't pass any value in `rows`, as those are empty objects. 

I've been looking at ways around this, and I'll keep working on it.
