### ISSUE TITLE
Failed licensing check (maybe?) causing website to hang

### ISSUE THREAD

**Issue by eriktdesign** [getblocklab/block-lab#397]
Our development environments were seeing super long load times and timeouts this morning. New Relic monitoring revealed external hits to getblocklab.com taking 40,000ms. The Block Lab website appears to be down today. Looking at source, I'm guessing the plugin is trying to re-validate my license, but the super-long timeout is causing the website to hang.

Disabling the Block Lab plugin (via CLI) resolved the issue.

**Comment by kienstra** [comment]
Hi @eriktdesign,
Thanks for bringing this up. We're working on it now.

Are you using the Pro version also? It looks like it is making requests to our site to validate the license that are failing, like you mentioned.

If you're using Pro, removing the license key for the moment should enable you to keep using the plugin.

The Pro fields will still render like before. The only change will be that you won't be able to change the block in `/wp-admin` > Block Lab > All Blocks:

<img width="1126" alt="change-here" src="https://user-images.githubusercontent.com/4063887/63630355-282ff300-c65d-11e9-87d5-af0ac7b639f8.png">

**Comment by kienstra** [comment]
Hi @eriktdesign,
Sorry about this.

For the moment, making this one-line edit will restore the full Pro functionality:

```diff
diff --git a/php/class-util.php b/php/class-util.php
index cbc00c4..bbe7bc5 100644
--- a/php/class-util.php
+++ b/php/class-util.php
@@ -29,7 +29,7 @@ class Util extends Component_Abstract {
         * @return bool
         */
        public function is_pro() {
-               return $this->plugin->admin->license->is_valid();
+               return true;
        }
```

This should prevent requests to server, as long as it's you're not on the `/wp-admin` > Block Lab > Block Lab Settings page.

Of course, this would be in a built version of the plugin, like one downloaded from WordPress.org.

When making that edit to this repo on GitHub, it'd be necessary to also build this plugin with:

`npm install && npm run dev`
