### ISSUE TITLE
Repeater row limit

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#399]
There should be a row limit to repeaters. Use case: Adding buttons to the bottom of a hero section. e.g. I might have a hero that allows for _up to_ 2 buttons.

**Comment by kienstra** [comment]
Hi @lukecarbis,
Were you thinking of something like this:
<img width="828" alt="max-row-here" src="https://user-images.githubusercontent.com/4063887/63901116-e25e8c00-c9c8-11e9-956f-5dd13ae06775.png">

Also, there should probably be feedback in the block editor when the row limit is reached. Maybe the + icon to add a new row would be disabled, with a popover on hover.

**Comment by lukecarbis** [comment]
More likely something like this:

![Screen Shot 2019-08-29 at 10 33 35 am](https://user-images.githubusercontent.com/1097667/63901575-7c194e00-ca48-11e9-81c5-f74e6136432a.png)

Worth mentioning, though, that while we do call them "rows" in the code, the word "Row" hasn't yet been used in a user facing way. We may yet want to change what we call them.

Potentially, we could just hide the new row icon, instead of disabling it with a notice. Easier, leaner, and I think achieves the same thing.

**Comment by kienstra** [comment]
Good ideas. The screenshot looks good.

If it's alright, I'll probably get to this after the blank row issue (#393), and the issue with changing the repeater name causing removing the sub-fields
