### ISSUE TITLE
Repeater row count

### ISSUE THREAD

**Issue by BenHarris** [getblocklab/block-lab#403]
Add the ability to get the number of rows in a repeater

**Comment by kienstra** [comment]
@BenHarris, thanks for opening this!

**Comment by kienstra** [comment]
@BenHarris,
Thanks for bringing this up.

Could you please elaborate on the use case of counting the number of rows?

No to say it's not useful, just trying to get a sense of relative priority for this issue.

Thanks, Ben!

**Comment by lukecarbis** [comment]
@BenHarris This isn't the most ideal, but it is possible to get the number of rows in a repeater using the `$block_lab_attributes` global:
```
global $block_lab_attributes;
if ( isset( $block_lab_attributes['repeater'] ) && isset( $block_lab_attributes['repeater']['rows'] ) ) {
    echo count( $block_lab_attributes['repeater-quarters']['rows'] );
}
```

That said, if there were some compelling use cases for knowing the repeater rows, I think creating a new helper function might make sense here instead.

**Comment by BenHarris** [comment]
In my use case, the site is using Bootstrap. If there were 1-2 elements, they should have a 50% width each (col-6), if there were 3, they should be 33% each (col-4). I achieved it in the end by just looping and counting, then a reset and re-looping.

**Comment by lukecarbis** [comment]
It would also be nice to get the current index while looping through.

**Comment by lukecarbis** [comment]
@BenHarris Another fairly easy way of getting the total rows is:

```PHP
$repeater = block_value( 'repeater' );
$rows     = count( $repeater['rows'] );
```

Do you think that's sufficiently easy, or should there be a helper function, such as:
```PHP
$rows = block_row_count( 'repeater' );
```

**Comment by BenHarris** [comment]
Nice work @lukecarbis :-)
