### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#41]
I get this error in the console whenever I add a block.

![screen shot 2018-08-02 at 6 34 06 pm](https://user-images.githubusercontent.com/1097667/43572415-cf048eb8-9682-11e8-9dde-563514bf3a70.png)

**Comment by rheinardkorf** [comment]
This is an easy fix... I forgot about the keying... Vue does it too.

**Comment by rheinardkorf** [comment]
Issue has since been resolved. Its already in `develop`.
