### ISSUE TITLE
Giant tooltip for move up/down on repeater

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#417]
![image](https://user-images.githubusercontent.com/1578148/64245916-316b6a80-cf4f-11e9-889a-916a667e73c1.png)
Guessing this is not meant to be this big.
On develop branch.

**Comment by lukecarbis** [comment]
They are meant to be that big. Unfortunately, using the default Tooltip component, we can't do anything to change the size. It's the same for all tooltips in Gutenberg.

<img width="490" alt="Screen Shot 2019-09-09 at 2 01 13 pm" src="https://user-images.githubusercontent.com/1097667/64502602-5fafc800-d30a-11e9-9298-f8e091213e2c.png">
<img width="423" alt="Screen Shot 2019-09-09 at 2 01 21 pm" src="https://user-images.githubusercontent.com/1097667/64502603-5fafc800-d30a-11e9-94d2-1a9575cd7141.png">
<img width="870" alt="Screen Shot 2019-09-09 at 2 01 41 pm" src="https://user-images.githubusercontent.com/1097667/64502604-60485e80-d30a-11e9-9ed8-44714db07053.png">
