### ISSUE TITLE
PHPCS is Throwing Errors

### ISSUE THREAD

**Issue by stevenkword** [getblocklab/block-lab#427]
PHPCS is throwing an error against the latest version of the WP Coding Standards.  It was addressed previously through the usage of phpcs:ignore, however I believe the ruleset namespaces have since changed have changed.  PR incoming.

**Comment by kienstra** [comment]
Hi @stevenkword, thanks for bringing this up. I'll look at this, and will look at your PR when it's ready.

**Comment by kienstra** [comment]
It looks like I should have included `phpcodesniffer-composer-installer` in `composer.json`, like how the [AMP plugin does](https://github.com/ampproject/amp-wp/blob/dcfa44ccfbbd083d302d7e2a58917966a6a0c984/composer.json#L20).

At least locally, `npm run lint:php` is passing with this diff:

```diff
diff --git a/composer.json b/composer.json
index 65c4261..fe7f046 100644
--- a/composer.json
+++ b/composer.json
@@ -8,6 +8,7 @@
         "php": "^5.6 || ^7"
     },
     "require-dev": {
+        "dealerdirect/phpcodesniffer-composer-installer": "0.5.0",
         "brain/monkey": "^2",
         "squizlabs/php_codesniffer": "^3.4",
         "wp-coding-standards/wpcs": "2.1.1"
diff --git a/phpcs.xml b/phpcs.xml
index b337e37..1088de7 100644
--- a/phpcs.xml
+++ b/phpcs.xml
@@ -2,7 +2,7 @@
 <ruleset name="WordPress Coding Standards for Plugins">
     <description>Generally-applicable sniffs for WordPress plugins</description>
 
-    <rule ref="WordPress" />
+    <rule ref="WordPress-Core" />
 
     <rule ref="WordPress.Files.FileName.InvalidClassFileName">
         <exclude-pattern>tests/*</exclude-pattern>
block-lab $
```

**Comment by kienstra** [comment]
**Question about phpcs**

Hi @stevenkword,
Hope you're doing great.

Were you able to run `phpcs` without error in this repo?

Doing `npm run lint:php` should run that command and shouldn't show any error or warning. As long as `composer install` was run at some point.

Thanks, Steven!
