### ISSUE TITLE
WPML Compatibility

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#428]
This might need to be via a separate helper plugin.

Since we're storing block configuration details as a JSON blob in post content, translating a block would be really difficult / not even possible right now.

Of course, translating blocks to multiple languages would be quite a common requirement.

**Comment by kienstra** [comment]
Ah, great point.

**Comment by marsjaninzmarsa** [comment]
Umm, where is the issue? 🙃
WPML is in own roots about translating post content, Gutenberg blocks utilizes post content... what do you mean by "translating block"? You want to translate titles and placeholders...?

**Comment by kienstra** [comment]
A user mentioned that WPML can't translate post content from Block Lab blocks:

https://wordpress.org/support/topic/translation-1091/

This might be a good one to investigate/work on after the React refactoring.

**Comment by igiornotigi** [comment]
Hi, I have the same problem with WPML. Some news?

**Comment by kienstra** [comment]
Hi @igiornotigi,
Thanks for bringing that up. There hasn't been any change since this issue was opened.

**Comment by kienstra** [comment]
Hi @igiornotigi,
Thanks for bringing that up. There hasn't been any change since this issue was opened.

**Comment by awa-cyberday** [comment]
Hi, I have the same problem with WPML. Some news?

**Comment by kienstra** [comment]
Hi @awa-cyberday,
Thanks for asking, but we're not maintaining Block Lab anymore.
