### ISSUE TITLE
Empty Rich Text field outputs </p>

### ISSUE THREAD

**Issue by DavidMillington-CD** [getblocklab/block-lab#437]
Hi, if you add a Rich Text field to a block but don't enter any text then it outputs a `</p>` tag in the frontend.  The expected behaviour would be a blank string similar to how the Text field functions.  This happens when the RTE is a top level field and also when it is added as a sub field to a repeater.

Black Lab 1.4.1

**Comment by kienstra** [comment]
Hi @DavidMillington-CD,
Thanks for opening this. I'll look at it.

**Comment by kienstra** [comment]
Thanks for opening this. I also see that a Rich Text control without any text entered in it unexpectedly outputs `<p></p>` on the front-end:

<img width="1244" alt="rt-control" src="https://user-images.githubusercontent.com/4063887/66091692-6ec31800-e54e-11e9-88c1-50b3c1172bb6.png">

**Comment by kienstra** [comment]
We might add a workaround to this, like in the `validate()` method of the `Rich_Text` control. But this issue doesn't exist with the WIP 'Classic Text' block in #432.

**Comment by DavidMillington-CD** [comment]
It's not just the fact it is outputting empty tags.  It's the fact it is outputting broken tags.  You are looking at it in the inspector which fixes the tag for the display it shows you e.g. `<p></p>`.   You have to view source on the actual broken code to see the real output which is just `</p>`:

- [Inspector View](https://i.imgur.com/FVLxf94.jpg)
- [Actual Outputted Code](https://i.imgur.com/qeQFEGr.jpg)

So my point is that it's not just outputting empty tags.  It is outputting invalid HTML.

**Comment by kienstra** [comment]
Hi @DavidMillington-CD,
Great point. You're right, only a `</p>` appears when the Rich Text field has no value:

<img width="528" alt="closing-p" src="https://user-images.githubusercontent.com/4063887/66258786-ee2f3200-e76e-11e9-9f89-7e0918a67620.png">

This looks to be from calling `wpautop( "<p></p>" )`, which is what the Rich Text control saves for an empty value:

<img width="982" alt="wpautop-here" src="https://user-images.githubusercontent.com/4063887/66258817-4b2ae800-e76f-11e9-887a-17941ab63b53.png">
