### ISSUE TITLE
Renaming repeater removes sub-fields

### ISSUE THREAD

**Issue by DavidMillington-CD** [getblocklab/block-lab#441]
If you create a block with a repeater and sub-fields, then later come back to it and rename the repeater and some of the sub-fields and save then the sub-fields will vanish.

**Comment by kienstra** [comment]
Hi @DavidMillington-CD, thanks for bringing this up. We've seen this also, but didn't find a quick solution.

Feel free to check back on this issue, a possible PR will reference it.

**Comment by lukecarbis** [comment]
This was resolved in #438.
