### ISSUE TITLE
slack invite link doesnt work any longer

### ISSUE THREAD

**Issue by torian257x** [getblocklab/block-lab#442]
https://block-lab.slack.com/join/shared_invite/enQtNjE1NjUxNDIzNTY4LWRlMzFjZTY3ZDJiZmI4YzhkYzMyMDZiMzNiZDc1ZGMyODA2Mjg3NzkyYzkwNDQwN2JkYjk3YzE2NjIyOGRlYTk

says invite link expired

from 

https://getblocklab.com/welcome-to-the-lab/

**Comment by lukecarbis** [comment]
Thanks for reporting this, @Jossnaz. I've updated the website with the correct link: https://join.slack.com/t/block-lab/shared_invite/enQtNjE1NjUxNDIzNTY4LTcyODQwMDE2ODZmODJiZTllZDJiODU0ZWQzNjg4YTkxM2EyODYxNWQ0YTA3MTI3NjBiNWQ4ZWIxYTlmYzE3YzU
