### ISSUE TITLE
polylang compatibility? multi language support

### ISSUE THREAD

**Issue by torian257x** [getblocklab/block-lab#443]
notice: I haven't written multilanguage pages yet with wordpress, only using wordpress literals e.g. properties, not entire pages

what about translating text and images in custom blocks?

or: how to support 30 languages with block labs blocks?

would polylang work well together with block labs?

**Comment by kienstra** [comment]
Hi @Jossnaz,
That's a good question.

Field values in Block Lab are saved just like any other block editor attributes for dynamic blocks. So I'd imagine they might have the same translation support in Polylang as other attributes. 

Though I don't know much about Polylang. Do you know how much Polylang supports the block editor in general?

<img width="901" alt="label-help-text" src="https://user-images.githubusercontent.com/4063887/66258596-bb843a00-e76c-11e9-8fdf-912d8b51b067.png">

Though the field labels and help text (that only appear in the block editor) probably aren't translatable yet. They're saved in [post content](https://github.com/getblocklab/block-lab/blob/cfde5541217361cdadf16ec8c17ff962a4bacfe9/php/blocks/class-block.php#L89).

The Repeater control is probably an exception to this, as it saves all of its fields in a single attribute.

You've probably looked at this more than me, but I couldn't find how much Polylang supports the block editor. You might have seen these, but they're pretty old:

https://wordpress.org/support/topic/polylang-and-gutenberg/
https://polylang.pro/polylang-2-5-and-wordpress-5-0/

**Comment by torian257x** [comment]
@kienstra actually my question was more basic. It would be interesting to look into translating the blocks as well but for my use case I needed polylang to work with the blocks one created. And it seems, that it does. E.g. we can create pages with blocks, and then translate the entire page using new blocks

**Comment by kienstra** [comment]
OK, that's good to hear!
