### ISSUE TITLE
Crashes site if administrator role renamed

### ISSUE THREAD

**Issue by DavidMillington-CD** [getblocklab/block-lab#445]
Hi, we use the Members plugin to manage user roles and permissions.  We have two levels of administrator and so renamed the default.  When we try to view the site we get the "The site is experiencing technical difficulties." message when trying to view any pages.  The error log shows:

PHP Fatal error:  Uncaught Error: Call to a member function add_cap() on null in [snip]/plugins/block-lab/php/post-types/class-block-post.php:243

So digging down to that line shows:

$admins = get_role( 'administrator' );

The only way I could get back into the admin was to move the block-lab directory outside the project, login to the WP admin and rename one of the two custom admin roles back to "administrator".  Then move the block-lab directory back.

It's quite common practise to rename the administrator account.

**Comment by kienstra** [comment]
Hi @DavidMillington-CD,
Wow, sorry about that. That sounds like a big hassle to get the site back up again.

Good point that the plugin should have better handling for that role. I'll work on this.

**Comment by kienstra** [comment]
Hi @DavidMillington-CD,
Wow, sorry about that. That sounds like a big hassle to get the site back up again.

Good point that the plugin should have better handling for that role. I'll work on this.

**Comment by kienstra** [comment]
I'm working on this now.
