### ISSUE TITLE
Memory leak when an empty Rich Text field loses focus.

### ISSUE THREAD

**Issue by lukecarbis** [getblocklab/block-lab#450]
I'm experiencing huge browser slow-downs when in the Gutenberg editor and a Rich Text field is blurred.

I've seen this error in my console:

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

Using Safari.

@kienstra Think you could take a look into this?

**Comment by kienstra** [comment]
Hi @lukecarbis,
Thanks for opening this. I'll work on this, though I might not start until the weekend if that's alright.

**Comment by kienstra** [comment]
Hi @lukecarbis,
Thanks for bringing this up.

Could you please help with a screenshot of the block where this error occurs? Is this for any 'blurring,' like clicking outside of the Rich Text field, or tabbing outside it?

I didn't see this issue in Safari or Chrome, though not to say it's not valid.

<img width="956" alt="rich-text-here" src="https://user-images.githubusercontent.com/4063887/67914519-00c23e80-fb56-11e9-8cc2-f1d93a1300ea.png">

The [Rich Text component](https://github.com/getblocklab/block-lab/blob/develop/js/blocks/controls/rich-text.js#L23) is pretty basic, nothing obvious comes to mind.

Thanks, Luke!

**Comment by lukecarbis** [comment]
I can no longer replicate this issue.

**Comment by kienstra** [comment]
All good, feel free to reopen it if you see it again.
