### ISSUE TITLE
Think through default for Classic Text field

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#458]
Not 100% sure if this is the best solution.
Not a bug, but maybe we do something different.
![image](https://user-images.githubusercontent.com/1578148/67671344-7e087a80-f9c1-11e9-8960-1e4b15d42f61.png)

**Comment by kienstra** [comment]
Hi @RobStino,
Thanks for opening this.

Is this issue only for the 'Default Value' field? Were you thinking of how that's simply an `<input>`, though the Classic Text field allows markup?

**Comment by kienstra** [comment]
If so, we should have some kind of resolution on this issue before the release. We don't want to change it later, and then break backwards compatibility.

**Comment by kienstra** [comment]
Hi @RobStino,
Good to see you a minute ago.

Per our discussion on Zoom, it sounds like we're going to keep this as is, and maybe later have more of a 'Rich Text' type editor for the Default field. 

Does that sound good?

**Comment by RobStino** [comment]
Sounds good!
