### ISSUE TITLE
Post field doesn't go 100% wide

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#459]
TBH, 100% wide would probably look not as good as it is, but it breaks the standardised UX of all the other fields.

We should either make them go 100% or remove the width settings from those fields

In Block Builder
![image](https://user-images.githubusercontent.com/1578148/67671579-ef482d80-f9c1-11e9-85d1-f84522140a1b.png)

In editor
![image](https://user-images.githubusercontent.com/1578148/67671599-f7a06880-f9c1-11e9-9f9b-2bbb6d209630.png)

**Comment by RobStino** [comment]
Noticed that this is the same for the taxonomy fields.

**Comment by kienstra** [comment]
Hi Rob, good find! Thanks for opening this.
