### ISSUE TITLE
Controls overlap with Rich Text

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#460]
The controls for the Rich text field overlap the field above.
![image](https://user-images.githubusercontent.com/1578148/67671679-228abc80-f9c2-11e9-8057-d102c683e69b.png)

**Comment by lukecarbis** [comment]
Just tested and the style is different again in 5.3. My suggestion is that we skip this for the current release, and make sure that it's addressed when working on a fix for #456.
