### ISSUE TITLE
Incremental Numbering for Duplicated fields not working - "Nan"

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#461]
This was working ok on the PR branch, but observing the following on the v1.5 version bump branch.
I confirmed I was on the right branch and that I had ran `nom run build`
![image](https://user-images.githubusercontent.com/1578148/67671958-9f1d9b00-f9c2-11e9-86b2-43412401065f.png)

**Comment by kienstra** [comment]
Hi @RobStino,
Thanks for opening this. Could you please add a few steps to reproduce? Thanks.

**Comment by lukecarbis** [comment]
OH NO! I can't reproduce!!

![Screen Shot 2019-10-29 at 7 30 32 pm](https://user-images.githubusercontent.com/1097667/67754675-98565d00-fa82-11e9-8acf-6274c46f927d.png)

**Comment by RobStino** [comment]
So, I'm testing this again this morning and without changing anything, I can't replicate...
I recommend we move forward with the release. If it's a real issue, it will surface again.
It's not going to break anything existing either as it will only surface (if it does) when people add/duplicate new fields.

**Comment by kienstra** [comment]
Sounds good, feel free to update this if you see it again.

**Comment by kienstra** [comment]
Closing this for now.

**Comment by lukecarbis** [comment]
Reopening since I managed to replicate it. Will post again with more details once I figure more out.

**Comment by lukecarbis** [comment]
Here's how to replicate the issue:

1. Add a field
2. Add another field, and manually give it the exact same field name
3. Duplicate one of those two fields
