### ISSUE TITLE
Theme Isle Block CSS Compatibility

### ISSUE THREAD

**Issue by pcfreak30** [getblocklab/block-lab#480]
Not sure if I need to bring this up with them (it's a free but very useful plugin).

Apparently using the `block-css` plugin on a get lab block throws an attribute error.

![Selection_301](https://user-images.githubusercontent.com/10647/69538021-5e785980-0f4f-11ea-9f5a-04e95d12c66e.jpg)

Everything else does work if I click to focus it, just not the preview.

**Comment by pcfreak30** [comment]
A bit of digging in the network calls to `/wp-json/wp/v2/block-renderer/block-lab/background-overlay?context=edit&attributes%5Bimage%5D=3920&attributes%5Bopacity%5D=0.5&attributes%5Bposition%5D=center%20center&attributes%5Brepeat%5D=no-repeat&attributes%5Bsize%5D=cover&attributes%5BhasCustomCSS%5D=false&attributes%5BcustomCSS%5D=&post_id=79&_locale=user` shows `hasCustomCSS is not a valid property of Object.`

**Comment by kienstra** [comment]
Hi @pcfreak30,
Thanks for bringing this up.

That message can be hard to debug. Does a message like that also appear with dynamic blocks in Core, like Latest Comments?

**Comment by kienstra** [comment]
https://github.com/getblocklab/block-lab/issues/375 might be related

**Comment by pcfreak30** [comment]
@kienstra i just checked in a dummy post and yes it does.

**Comment by kienstra** [comment]
OK, thanks. It might be good to raise that with the `block-css` plugin, or with Gutenberg.
