### ISSUE TITLE
[Question] Dependencies

### ISSUE THREAD

**Issue by lonix1** [getblocklab/block-lab#491]
Does a custom block created with this plugin depend upon the plugin?

So does the plugin need to be installed in order for the custom block to be rendered correctly?

**Comment by kienstra** [comment]
Hi @lonix1,
Yes, a block created with Block Lab depends on the plugin, and the plugin needs to be installed.

It wouldn't be too hard to reimplement the front-end of the block as a [dynamic block](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/), and deactivate this plugin. But reimplementing the block editor JavaScript would probably be harder.

For example, if the block's slug is `test-hero`:

```
add_action(
  'init',
  function() {
     register_block_type(
        'block-lab/test-hero',
        [
            'attributes' => [
                'headline' => [
                   'type' => 'string',
                ],
                ...
            ],
            'render_callback' => 'my_render_test_hero',
        ]
        ...
```

This plugin saves the block data just like any other dynamic block, in the block attributes. For example:

```
<!-- wp:block-lab/test-hero {"headline":"This is an example headline","copy":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.","url":"https://example.com/baz"} /-->
```

**Comment by lonix1** [comment]
Thanks

**Comment by kienstra** [comment]
Sure! Thanks for using Block Lab.
