### ISSUE TITLE
Consider using bot to automatically open PRs to update dependencies

### ISSUE THREAD

**Issue by kienstra** [getblocklab/block-lab#493]
It'd be great to automate updating the versions in `package.json` and `composer.json`. 

The AMP plugin has been using the free [renovate bot](https://github.com/marketplace/renovate), which automatically [opens PRs](https://github.com/ampproject/amp-wp/pull/3993) to update `composer.json` and `package.json` versions, and their corresponding lock files. 

Though I don't think it's owned by Google, it's [owned by WhiteSource](https://renovate.whitesourcesoftware.com/).

Here's an example of the configuration: https://github.com/kienstra/augmented-reality/pull/17

A possible risk is that we're giving it these permissions:

<img width="597" alt="renovate-permissions" src="https://user-images.githubusercontent.com/4063887/71206687-c2e6ba00-226a-11ea-9975-92683b6facd3.png">

It only [opens PRs](https://github.com/kienstra/augmented-reality/pull/22), it doesn't merge them unless we configure it that way.

Maybe someone could use it to maliciously push code to our repo. But the biggest vulnerability would be our WordPress.org SVN repo, and we review the diff before pushing there. 

**Luke, if you agree with this, maybe we could have a 10-minute Zoom call sometime where you set this up. I think your repo permissions are required for this.**

**Comment by kienstra** [comment]
Hi @lukecarbis,
Good to see you yesterday.

What do you think about this? It should make it much easier to keep the dependencies up to date.

Thanks, Luke!

**Comment by kienstra** [comment]
Also, plan on filtering emails from WhiteSource sales, I've gotten a few emails asking for a demo meeting to see their other products, since using `renovate` on one of my personal repos.

**Comment by lukecarbis** [comment]
I'd suggest considering [`dependabot`](https://github.com/marketplace/dependabot-preview) (used by Mozilla and Shopify).

Dependabot is owned and maintained by GitHub.

**Comment by kienstra** [comment]
Ah, good idea. I'll look at that.

**Comment by kienstra** [comment]
Thanks for suggesting [dependabot](https://github.com/marketplace/dependabot-preview). I'm testing it on one of my own repos, here's an example PR: https://github.com/kienstra/augmented-reality/pull/37

It's been working well so far, and no spam emails yet.

If it keeps going well in a few days, maybe I'll ask if I can activate it on Block Lab.

The permissions look similar to the `renovate` bot:
<img width="625" alt="dependabot-permissions" src="https://user-images.githubusercontent.com/4063887/72945305-1ef89e80-3d41-11ea-8d3f-110a5cbbe9e7.png">

**Comment by kienstra** [comment]
@lukecarbis,
Hope you're doing great. 

What do you think about activating [dependabot](https://github.com/marketplace/dependabot-preview) on Block Lab after https://github.com/getblocklab/block-lab/pull/502 is merged for the `1.5.3` release?

It's been working well on one of my plugins for the past 3 days. Here are [some PRs](https://github.com/kienstra/augmented-reality/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies) it opened.

There were a lot the first day, but there have been none the last 2 days. And no spam so far 😄 

I think something like this is essential to keeping versions up to date. 

Thanks, Luke!

**Comment by lukecarbis** [comment]
Let's do it. :)

**Comment by kienstra** [comment]
Sounds good!
