### ISSUE TITLE
Export block as stand-alone plugin.

### ISSUE THREAD

**Issue by rheinardkorf** [getblocklab/block-lab#50]
It would be nice if there was a way to export a block as a standalone plugin with minimal scaffolding required.

It would still need to maintain the current acb_locate_template() mechanism and template loader.

**Comment by lukecarbis** [comment]
The more I think about this, the more I think this should be an add-on plugin. So, you'd install Block Lab + Block Lab Plugin Exporter, and do it that way.

@RobStino Thoughts?

**Comment by RobStino** [comment]
I think this should be stand-alone as well. It's not core functionality and is something that only _some_ people would want _some_ of the time. Anything that falls in to this kind of category should be an extension. Somewhat like the WordPress Core features / Plugin features distinction.

**Comment by markusb** [comment]
Just want to say that I'm looking for the same functionality. Block lab is an excellent way to quickly create a new block, but I'd want the new block to be in a custom plugin and not tied to block lab. This allows me to develop in my dev environment and move just my custom plugin into production, with no other prerequisites.

**Comment by x5hwuk7nc6jsudcc** [comment]
Is anyone working on this as a standalone plugin? Link to repository?
