### ISSUE TITLE
How can i create a group block on block-lab

### ISSUE THREAD

**Issue by nguyendinhkhanh91** [getblocklab/block-lab#501]
I want to create group block by using block-lab ( same as Gutenberg group block, but i want to custom css, html tag by myself). How can i do that. If current version can do that, please tell me how, if not please add this feature, i think it should be have.

**Comment by kienstra** [comment]
Hi @nguyendinhkhanh91,
Thanks for bringing that up. 

Have you tried creating a Core Group block and adding Block Lab blocks to it? 

Block Lab doesn't have a specific 'Group' field, though.

**Comment by kienstra** [comment]
https://github.com/getblocklab/block-lab/issues/474 may be related to this.

**Comment by nguyendinhkhanh91** [comment]
@kienstra i haven’t time to research core code of this plugin. Currently i have to use group block of gutenberg, and use default class name of it to customize css

**Comment by nguyendinhkhanh91** [comment]
@kienstra thank for your mention. I read that issue, but in my case it’s more difficult. I want to create a custom group block, and  Add multi blocks in this (example: multi gutenberg block in this)

**Comment by kienstra** [comment]
OK, that sounds good. Feel free to download this plugin and see if it helps. 

If a Group field would help, feel free to comment on #474, or open a separate issue if you're thinking of something different.

**Comment by nguyendinhkhanh91** [comment]
@kienstra actually i want to create a custom group block, which i can add others block in, on gutenberg editor

**Comment by kienstra** [comment]
OK, Block Lab doesn't have a field for that, at least yet.

**Comment by kienstra** [comment]
So this Group block could add any block to it, from Core, Block Lab, or otherwise?

**Comment by kienstra** [comment]
Closing now, but feel free to respond here or add to #474
