### ISSUE TITLE
Error loading block: Invalid parameter(s): context in Wordpress 5.3.2

### ISSUE THREAD

**Issue by c-abird** [getblocklab/block-lab#504]
The above error is displayed in the Gutenberg editor for any block-lab block that is not selected. The block shows fine in the frontend. The error occurs for all blocks, including blocks without any fields. According to #244, the plugin was installed via the Wordpress backend.

**Comment by lukecarbis** [comment]
@c-abird Could you please attach a screenshot of your console output?

**Comment by c-abird** [comment]
@lukecarbis thanks for the quick reply. What do you mean by "console output" (Sorry, I'm fairly new to Wordpress). I'm attaching a screenshot of the editor showing the error. There are no errors in the server logs.
![wp_error](https://user-images.githubusercontent.com/345979/72678216-349d6800-3aa4-11ea-8272-317d8ab76144.png)

**Comment by kienstra** [comment]
Hi @c-abird,
Depending on the browser, it might be something like View > Developer > JavaScript Console. It should look something like this:

<img width="1058" alt="console-js" src="https://user-images.githubusercontent.com/4063887/72684456-31a37700-3aa6-11ea-9153-6635fdd03897.png">

Also, is there any other block-related plugin active, and is the Gutenberg plugin active?

**Comment by c-abird** [comment]
Ah, I see, thanks for the hint. There is a JSON request to the URL
```http://example.com/wp-json/wp/v2/block-renderer/block-lab/teaser?context=edit&post_id=2&_locale=user```
("teaser" is the name of the custom block. Note, that I aliased example.com with my local host). This request leads to a 400 response with the following content:
```{"code":"rest_invalid_param","message":"Invalid parameter(s): context","data":{"status":400,"params":{"context":"context is not one of edit."}}}```

The console output looks like this:
![wp_error](https://user-images.githubusercontent.com/345979/72684652-d2b02300-3ae2-11ea-86b1-a4f404ef360a.png)

**Comment by c-abird** [comment]
Hi @kienstra. Thanks for your input, see message above. Concerning additional plugins, I deactivated all block related plugins (namely "Ultimate Addons for Gutenberg"), but still getting the same error.

**Comment by kienstra** [comment]
Hi @c-abird,
Thanks a lot for the console output. That helps.

Sorry to keep asking for more, but would you be able to paste here the PHP template code for the block, and a screenshot of the block configuration?

For example, here's a block configuration:

<img width="1329" alt="example-block-configuration" src="https://user-images.githubusercontent.com/4063887/72686642-85b95600-3abc-11ea-8262-649d87505e8c.png">

**Comment by c-abird** [comment]
Hi @kienstra. Thanks for your help! 
I've tried multiple templates and configurations (including a block without any variables + static template). I attached a very simple block. As previously mentioned, the block itself is working perfectly in the frontend. Just the rendering in the editor seems to be broken if the block is not highlighted for editing.

![wp-error1](https://user-images.githubusercontent.com/345979/72686796-866fdd80-3af8-11ea-8981-f9da9400000d.png)
![wp-error2](https://user-images.githubusercontent.com/345979/72686797-87087400-3af8-11ea-9743-ba5c52d9b4fe.png)

**Comment by kienstra** [comment]
**Update: please ignore this**

Thanks, @c-abird! 

The configuration and template look good, they don't look to be causing the issue.

Is the Gutenberg plugin active, by chance? If not, could you try activating it the latest released version?

There was a fix for an issue similar to this that was merge last month:

https://github.com/Codeinwp/gutenberg-css/pull/12

**Comment by kienstra** [comment]
Ah, sorry. The fix above was in a separate plugin, not Gutenberg.

It looks like the Gutenberg issue similar to this is still open: https://github.com/WordPress/gutenberg/issues/16850

**Comment by kienstra** [comment]
After the following steps, does that same error still appear?

1. Deactivate all block-related plugins (with Gutenberg active if you'd like)
2. Create a new simple Block Lab configuration, like 'Foo Block'
3. Click 'New Post,' and add that 'Foo Block'
4. Edit that block
5. Does that error still appear?

This error might be from another plugin adding something to the block: https://github.com/WordPress/gutenberg/issues/16850

They might persist even after another plugin is deactivated.

**Comment by kienstra** [comment]
If the steps above don't help, does this same issue occur with the Core 'Latest Comments' block? That also uses the `<ServerSideRender>` component that Block Lab uses.

**Comment by c-abird** [comment]
Hi @kienstra. Thanks for the hints. Indeed, the "Latest Comments" block produces exactly the same error. So, I guess this means that there is a problem with my Wordpress installation, right?

**Comment by kienstra** [comment]
Hi @c-abird,
Yeah, it's more likely to be a general problem with WordPress Core or Gutenberg, not Block Lab in particular. 

Does this error appear for the 'Latest Comments' block if all plugins are deactivated, including Block Lab? If so, [opening an issue](https://github.com/WordPress/gutenberg/issues/new/choose) with Gutenberg is probably appropriate.

**Comment by fredrik-luckan** [comment]
Hello I have the same problems , screenshot of console below. No Gutenberg plugin installed. 
![Screenshot 2020-01-31 at 11 08 22](https://user-images.githubusercontent.com/60471253/73526511-16c3f180-441a-11ea-8ebb-2965ba2ee9b2.png)

**Comment by kienstra** [comment]
Hi @fredrik-luckan,
Thanks for bringing that up. Could you please open a new [bug issue](https://github.com/getblocklab/block-lab/issues/new?template=bug_report.md) so we can look at the specific issue you have?

Maybe it is the same as this issue, but more details would really help.

**Comment by fredrik-luckan** [comment]
ok I posted a bug

**Comment by kienstra** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/16850.
