### ISSUE TITLE
Block with Classic Text Sub-Element in Repeater Element Isn't Able To Open With Chrome Browser

### ISSUE THREAD

**Issue by CarloMagneti** [getblocklab/block-lab#505]
## Bug summary

i've build an block with a repeater element and several Classic text elements in it, and it's working in firefox perfectly. In Chrome the problem is that the block in the backend closes directly when i click into it. When i change the Classic text element to Rich Text i can edit the Block in the Backend editor.

## Steps to reproduce

1. Build a new block
2. Add an repeater element
3. Add a Classic Text sub-element.
4. Create the css and php file to display the block
5. Insert the Block on a page in the backend gutenberg editor
6. Try it with Firefox and Chrome

## Expected behavior
The block should be editable in both browsers

## Actual behavior
 
The Block Edit Screen always tries to open and closes again in Chrome

## Suspected cause (optional)
 
The Classic Text element.

## Versions

 - WordPress version: 5.3.2
 - Block Lab version:  1.5.2
 - Gutenberg plugin version (if active):
 - OS: MacOS Catalina 10.15.2 
 - Browser: Firefox and Chrome
 - Device:  MacBook

**Comment by kienstra** [comment]
**Thanks!**

Hi @CarloMagneti,
Thanks for your detailed report.

I can't yet reproduce this, but it does sound like a bug with something.

![repeater-si](https://user-images.githubusercontent.com/4063887/72691998-16a92500-3aef-11ea-9b11-59aec16ca6e5.gif)

Are there any errors or warnings in the JS console when this issue occurs?

**Comment by CarloMagneti** [comment]
Hi and thanks for your fast response.
My block editor backend looks like the screenshot. There are more than classic blocks, but if i'm changing the classic editor block to rich editor, than it works in Chrome. The error log shows some errors with the tinymce:

![Bildschirmfoto 2020-01-20 um 11 23 34](https://user-images.githubusercontent.com/8616094/72718991-4d2a8280-3b77-11ea-8a84-699d057bfbc7.png)

So if i'm deactivate my TinyMCE Plugin, it works. Hmm, do you see a possibillity that the Classic Editor Block works in correspondance with the TinyMCE Plugin in Chrome as well as in Firefox?

With best regards, 
André

**Comment by CarloMagneti** [comment]
Ok it's a thing with the tinyMCE plugin settings. If i am deactivate the hybridmodus to set the classic block as standard than it works fine. Thanks for your work and your time and sorry for the hassle. But maybe another users make the same experiences, than you know the error :)

**Comment by kienstra** [comment]
Thanks for noting here how you resolved this!
