### ISSUE TITLE
Error loading block: parameter(s): attributes

### ISSUE THREAD

**Issue by fredrik-luckan** [getblocklab/block-lab#513]
## Bug summary

In the Gutenberg backend its shown like this: 
![Screenshot 2020-02-03 at 13 02 23](https://user-images.githubusercontent.com/60471253/73648160-999cb480-4685-11ea-9936-4e8758489241.png)
But in editing it works fine, and shows up on frontend.

## Steps to reproduce

![Screenshot 2020-02-03 at 13 10 18](https://user-images.githubusercontent.com/60471253/73648582-8dfdbd80-4686-11ea-96e2-cb4127ee09be.png)

Block code:
```
<div  class="hero-fiftycontainer alignfull nomarginhero" 
      style="background-color:<?php block_field( 'hero-bgcolor' ); ?> !important;
            flex-direction: <?php block_field( 'hero-flip-order' ); ?>;">
    <div class="hero-left-side">
      <article class="left-text">
       <h1><?php block_field( 'hero-titel' ); ?></h1>
       <p><?php block_field( 'hero-undertext' ); ?></p>
     </article>
  </div>
    
     <img class="right_image right-half" 
              src="<?php block_field( 'hero-half-image' ); ?> "
              style=
              "object-fit: <?php block_field( 'toggle-contain-image' ); ?>;
              padding: <?php block_field( 'margin-image' ); ?>px;"> 
  </div>
```

## Expected behavior
To show up as a working block
![Screenshot 2020-02-03 at 13 16 01](https://user-images.githubusercontent.com/60471253/73648959-60fdda80-4687-11ea-9414-959a4ec91334.png)

## Actual behavior
![Screenshot 2020-02-03 at 13 07 15](https://user-images.githubusercontent.com/60471253/73648396-2182be80-4686-11ea-8afe-cb20d39e9c81.png)

## Suspected cause (optional)
cant figure out if user error or not. 

## Versions

 - WordPress version:
 - Block Lab version: Version 1.5.2
 - Gutenberg plugin version (if active): not active
 - OS: macos 10.15
 - Browser: Chrome
 - Device:  like MacBook

**Comment by kienstra** [comment]
Hi @fredrik-luckan,
Thanks for bringing this up.

Are there any other block-related plugins active?

**Comment by kienstra** [comment]
Hi @fredrik-luckan,
Thanks for your great report here.

Are there any other block-related plugins? That error is unfortunately hard to debug. 

It looks like your PHP template is fine.

**Comment by kienstra** [comment]
Closing now for lack of activity, but feel free to reopen with more information.
