### ISSUE TITLE
block_field() glitch

### ISSUE THREAD

**Issue by shadeydave** [getblocklab/block-lab#516]
## Bug summary

#kienstra
I'm running into an issue where the "block_field('fieldname', false);" is still rendering the block content. I need it to omit some code if the block is empty. Which it does when I use it in an "if" statement. But when the field contains content, it's rendering the field content where I'm doing the value check. So, I'm getting extra floating field values on the page. Is this a bug or am I doing something wrong?

## Steps to reproduce

1. create a block.php file with a field to check. "cta".
2. try to do a boolean validation to discern if it has content or not. If it does contain content, display the content in its proper context.
`<?php
$url = block_field( 'cta', false );
$figure = block_field('figure', false);
if ( ! empty( $url ) ) {
    echo '<a class="button" href="'.block_field('cta').'">'.block_field('cta-text').'</a>';
}
if ( ! empty( $figure ) ) {
    echo '<figure><img src="'.block_field('figure').'" style="width:100%;"/></figure>';
}
		?>
`
3. view the page.

## Expected behavior
The page should render and ONLY the field values in context should show on the screen. In the case above it should only show the link with a populated URL and link text.

## Actual behavior
 
![image](https://user-images.githubusercontent.com/11837198/76028686-1af39b00-5f01-11ea-8e75-773cf10b3ba5.png)
![image](https://user-images.githubusercontent.com/11837198/76028760-3e1e4a80-5f01-11ea-87da-222bbd22c2af.png)

Note the preceding duplicate values just sitting loose on the page just before their associated elements.

## Additional information
Here is the block configuration:
![image](https://user-images.githubusercontent.com/11837198/76029730-103a0580-5f03-11ea-8f0e-2110432ad0ba.png)

## Suspected cause (optional)
I'm doing this on a "URL" type and an "image" type. Perhaps the boolean modifiers don't exist for these types? 

## Versions

 - WordPress version: 5.3.2
 - Block Lab version: 
 - Gutenberg plugin version (if active):
 - OS: MacOS Catalina
 - Browser: Chrome (latest)
 - Device: Mid 2017 Macbook Pro

**Comment by kienstra** [comment]
Hi @shadeydave!

Thanks for opening this. Your template looks fine, I don't think the problem is on your end.

What are the types of these `cta`, `figure`, and `cta-text` fields? Are they all text fields?

![fi-text](https://user-images.githubusercontent.com/4063887/76029505-3ad39080-5efa-11ea-9224-0e95f8dc6c61.png)

**Comment by kienstra** [comment]
Also, what version of Block Lab is active?

**Comment by shadeydave** [comment]
Block Lab version: 1.5.3
I've edited the issue above to include the block configuration info.
![image](https://user-images.githubusercontent.com/11837198/76029914-5becaf00-5f03-11ea-86e9-f36ea37e60eb.png)

**Comment by kienstra** [comment]
OK, thanks. I'll work on reproducing this.

**Comment by kienstra** [comment]
Hi @shadeydave ,
Thanks for all of your details.

In the template, could you please try replacing all of the `block_field()` calls in the `echo` statements with `block_value()`, with the same arguments?

This doesn't doesn't look to be related to the conditional, the rest of the code looks fine.

Because these are already in an `echo` statement, simply getting the values with `block_value()` should be enough:

```php
	echo '<a class="button" href="'.block_value('cta').'">'.block_value('cta-text').'</a>';
	...
	echo '<figure><img src="'.block_value('figure').'" style="width:100%;"/></figure>';
```

**Comment by shadeydave** [comment]
@kienstra  It worked great for the "URL" field. But the "image" field just returns a value of "99" when I use "Block_value()".

I found a solution though. If you take the block_field('figure') out of the echo statement and sit it alone on its own line, it works fine. 
<code>
`if ( ! empty( $figure ) ) {
    echo '<figure><img src="';
    block_field('figure');
    echo '" style="width:100%;"/></figure>';
}
`</code> @

**Comment by kienstra** [comment]
Nice, thanks for trying that.

Yeah, I forgot that the image field has different output for `block_value()` and `block_field()`.
