### ISSUE TITLE
Can't use Number in Block Slug

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#53]
I noticed that although I could successfully save a custom block with a number character in the slug, as well as set up the template file, the block was not accessible in the GB editor. After changing the slug (removing number), and updating the template to match I was able to access it in the editor.

**Comment by rheinardkorf** [comment]
@RobStino was it a number prefix? Or any number?

**Comment by RobStino** [comment]
The slug was
`section-50-50`
The Block Title was
`Split Section 50/50`

**Comment by lukecarbis** [comment]
I can't replicate this on `develop`. @RobStino Can you try this again on `develop`, and report back?

**Comment by RobStino** [comment]
@lukecarbis I'll wait until those few PR's go through and then test.
