### ISSUE TITLE
Browser Refresh Warning Bug when embedding YouTube iFrame

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#54]
Video screen recording of issue -> https://d.pr/v/voYvBl

**Comment by rheinardkorf** [comment]
Is it specifically related to ACB?  What about a different browser?

**Comment by RobStino** [comment]
Issue tested in Chrome, FF, and Safari, but only observed in Chrome.
Also tested embedding the same YouTube video via
- YouTube Embed Block (Core)
- HTML Block (Core)
- Code Block (Core)
None of these caused the strange refresh behaviour.
Am still observing the issue as well. Just re-checked.

**Comment by lukecarbis** [comment]
Best fix for this might be applying `wp_kses_post()` to any content received through the template (at least when previewing in the editor). I don't believe iframe's are allowed.

**Comment by lukecarbis** [comment]
I couldn't replicate this issue on the latest version of Gutenberg. Do you want to give it another try?

**Comment by RobStino** [comment]
So have tested this now and the issue is no longer there. I'm spotting something else in relation to iFrames, but will close this issue and create another.
