### ISSUE TITLE
Programmatic declaration

### ISSUE THREAD

**Issue by MrZyr0** [getblocklab/block-lab#555]
## Feature description
The possibility to bypass bloc administration from the BO of WP by masking it and declare blocks in functions.php of my theme

## Use case

Usefull for customer website. This way the created blocks will be declared with the theme, no matter where it is used and users who don't know the code won't be able to modify them. This avoids a lot of problems.

**Comment by lukecarbis** [comment]
Hi @MrZyr0 – this feature already exists. You can read more about our PHP API here: 
- https://getblocklab.com/docs/functions/block-lab-add-field/
- https://getblocklab.com/docs/functions/block_lab_add_block/
