### ISSUE TITLE
Multiple blocks creation

### ISSUE THREAD

**Issue by MrZyr0** [getblocklab/block-lab#556]
## Feature description
It seams that we can't natively use multiples blocks 🤔 

## Image
When we follow the doc  (as I understand) :
![image](https://user-images.githubusercontent.com/32927775/80996980-feaca580-8e40-11ea-8f12-32addc16d601.png)

But the path shown when we create the block lets you understand the opposite:
![image](https://user-images.githubusercontent.com/32927775/80997123-2d2a8080-8e41-11ea-83a2-8a09ab85cb2f.png)

Here is my test (with multiple blocks):
![image](https://user-images.githubusercontent.com/32927775/80997208-46333180-8e41-11ea-9d01-807d0bdd2ea9.png)

I'm getting this error message:
![image](https://user-images.githubusercontent.com/32927775/80996664-7e864000-8e40-11ea-99b3-89f88613ba6e.png)

**Comment by lukecarbis** [comment]
@MrZyr0 The setup you're trying for does work, but it needs the following file structure in your theme:
```
/imagineo/blocks/imagineofirst/block.php
/imagineo/blocks/imagineofirst/block.css
/imagineo/blocks/imagineosecond/block.php
/imagineo/blocks/imagineosecond/block.css
```

Hope that helps!
