### ISSUE TITLE
Export/import feature

### ISSUE THREAD

**Issue by antti-tolvanen** [getblocklab/block-lab#563]
## Feature description
A possibility to export and import all blocks you the user has created.

## Image
-- No image --

## Use case
This feature will be useful for WordPress website developers for using designed custom Gutenberg blocks in several projects.

**Comment by kienstra** [comment]
Hi @antti-tolvanen,
Thanks for bringing this up.

This is possible with a Pro license: https://getblocklab.com/docs/get-started/export-custom-block-lab-blocks-to-include-in-your-theme/

Though unfortunately, we're not selling new pro licenses now.
