### ISSUE TITLE
Review escaping functions.

### ISSUE THREAD

**Issue by rheinardkorf** [getblocklab/block-lab#60]
E.g. https://github.com/rheinardkorf/advanced-custom-blocks/blob/develop/php/post-types/class-block-post.php#L173

Should be `esc_attr_e`.

**Comment by lukecarbis** [comment]
Never heard of it! Can't find any docs either: 
https://duckduckgo.com/?q=%22esc_attr_er%22

**Comment by lukecarbis** [comment]
Oh, you mean `esc_attr`, not `esc_html`.

**Comment by pedro-mendonca** [comment]
Hi, just made a PR #64 that solves this issue.

**Comment by rheinardkorf** [comment]
thanks @pedro-mendonca
