### ISSUE TITLE
Import/Export Function

### ISSUE THREAD

**Issue by jstrobel** [getblocklab/block-lab#622]
## Feature description
It would be nice to have a Import/Export-Feature to use the blocks in new installations in an easy way again.

**Comment by kienstra** [comment]
Hi @jstrobel,
Thanks for opening this. Would that be different from the existing export/import?

Export: https://getblocklab.com/docs/get-started/export-custom-block-lab-blocks-to-include-in-your-theme/

Import: https://github.com/getblocklab/block-lab/pull/449#issuecomment-557861481

**Comment by jstrobel** [comment]
Hi @kienstra thanks for your reply. Yes that is what i searched for.

The page you send isn't linked in the navigation is that correct?
And where do i find information about the pro version? Cannot find any info on the page - thanks.

**Comment by kienstra** [comment]
Hi @jstrobel,
Yeah, it's not linked in the main navigation, only under Docs > Getting Started:

<img width="959" alt="docs-getting-started" src="https://user-images.githubusercontent.com/4063887/85302510-d9b2d700-b46e-11ea-91cd-421b4ea707f9.png">

Sorry, we're not selling the Pro version of Block Lab anymore. But we're working on a new plugin with all of the features of Block Lab that will have the Pro features. There will also be a migration path:

https://getblocklab.com/the-block-lab-team-are-joining-wp-engine/

**Comment by jstrobel** [comment]
Thanks a lot for the explanation. Will have a look at the future.

**Comment by kienstra** [comment]
Sure, I can ping you here when the new plugin is ready if you'd like.
