### ISSUE TITLE
My custom blocks not available in “Add block” menu (after update?)

### ISSUE THREAD

**Issue by robs23** [getblocklab/block-lab#634]
## Bug summary

My custom blocks not available from Gutenberg block menu at adding new post. It used to work but from not any more. I can see my blocks in "Block Lab" tab in the dashboard and in blocks folder inside my theme.

## Steps to reproduce

Go to "Posts" -> "New post" from WP dashboard.

## Expected behavior

You can choose your custom blocks created with Block lab from "Add block" Gutenberg menu

## Actual behavior
None of my custom blocks appear on the "Add block" menu

## Additional information
2 warnings in JS console when "Add post" page is loading:
DevTools failed to parse SourceMap: https://aska-knives.pl/wp-content/plugins/block-lab/css/blocks.editor.css.map
post-new.php:1
Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq) <input type=​”hidden” id=​”_wpnonce” name=​”_wpnonce” value=​”bad709c0e8″>​ <input type=​”hidden” id=​”_wpnonce” name=​”_wpnonce” value=​”623962739b”>​

## Suspected cause (optional)
I suspected XO Featured Image Tools plugin might be the culprit, but deactiviating it didn't help.

## Versions

 - WordPress version: 5.0.10
 - Block Lab version: 1.5.5
 - Gutenberg plugin version (if active):
 - OS: Windows 10
 - Browser: Chrome
 - Device: Hp elitebook

**Comment by lukecarbis** [comment]
@robs23 Could you post your block template code here please?

**Comment by kienstra** [comment]
Thanks a lot for opening this!

Would you be able to update the WordPress Core version to the latest, `5.4.2`? 

The version of `5.0.10` is pretty old. I'm not sure if that's causing this, though.

**Comment by kienstra** [comment]
If that doesn't work, could you please post a screenshot of one of the Block Lab configurations? 

Like:

![example-block-config](https://user-images.githubusercontent.com/4063887/85973416-4448a300-b998-11ea-9c93-3ca6975efedd.png)

This could help me reproduce this.

**Comment by robs23** [comment]
Thanks for all the pointers, updating WP to 5.4.2 did the trick. Sorry, it's embarrassing really, I had auto WP updates off for some reason.. I wouldn't have thought it could cause that, though.
I can see, however, that using XO Featured Image Tools plugin made my "foto" image field in my custom block empty.
In visual editor I see: 
![image](https://user-images.githubusercontent.com/4737758/86018198-4b69c280-ba25-11ea-9b6a-4fe80a87776b.png)
And in code editor the field has disappeard all over:
`<!-- wp:block-lab/knifedetails {"nazwa":"Blue Star","stal":"M 390 60-62 HRC","dlugoscostrza":"105 mm","szerokoscostrza":"24 mm","gruboscklingi":"3,5 mm","rekojesc":" nowe srebro, fibra, heban, stabilizowana czeczota brzozy, pin dzik. Pochewka skóra farbowana."} /-->`
This is clearly caused by the plugin as it takes the first image on the page and make it post's feature image.. and now all first images (which happen to be "foto" images) don't appear in the post at all. Do you have any idea why's that? I would still like to use the plugin..

**Comment by kienstra** [comment]
Hi @robs23,
Thanks for trying the later WordPress version. No problem, it's not easy keeping it up to date with all of the changes.

Hm, I'm not sure why 'XO Featured Image Tools' is removing the `'foto'` field. Like you posted, it doesn't appear in the JSON blob in `<!-- w:block-lab/knifedetails`, so I'm not sure that's something I could fix. 

Would you be able to ask them about that?

Thanks for your patience.

**Comment by robs23** [comment]
Sure, I will ask them. What's puzzling me, every post in the blog has to language versions - polish and english. The weird thing is that all the 'foto' images are missing only in polish versions, english versions have 'foto' intact. I was thinking that maybe the plugin didn't process those, but not, since all of english versions have feature image set properly too.. Besides, for some polish blog posts I can't find the image using exact file name taken from feature image.. I can find it when I browse (or search by name) in Media tab, it is marked "Polish", so it should be all ok:
![image](https://user-images.githubusercontent.com/4737758/86232625-83dbde80-bb94-11ea-9b95-de808cda8238.png)
When browsing from my custom block  (knifedetails) "Media Library" button, the file can't be found:
![image](https://user-images.githubusercontent.com/4737758/86232919-f77deb80-bb94-11ea-9212-a010ca0ffda8.png)

EDIT: Here's a [link ](https://wordpress.org/support/topic/the-image-set-as-featured-by-your-plugin-cant-be-found-from-block-lab/)to XO Featured Image Tools's support forum.

**Comment by robs23** [comment]
Not sure if you've been following the discussion with XO Featured Image Tools author, but it's not getting anywhere to be honest.  On second thought, I'm not sure if it's related to the plugin all over. The thing is all the media files ARE there in the media library, it's just only that I can't find them in "Media library" opened from my custom block.. It's like "Media library" in my custom block's image field doesn't list all the files the regular "Media library" does. I even tried to edit the post in code, but when I add "foto":"https://aska-knives.pl/wp-content/uploads/2019/06/TRAPER-6", to:
`<!-- wp:block-lab/knifedetails {"nazwa":"Traper","stal":"D2 58-60 HRC","dlugoscostrza":"110 mm","szerokoscostrza":"24 mm","gruboscklingi":"3,5 mm","rekojesc":"garda- stal D2,miedź, przekładki fibra, stabilizowane drewno zebrano ( x-cut)","inne":"pochewka skóra farbowana z tłoczeniem"} /-->` the line gets deleted when I save the changes.. How I can set the correct file if I can't refer it in my custom block?

**Comment by kienstra** [comment]
Hi @robs23,
>The thing is all the media files ARE there in the media library, it's just only that I can't find them in "Media library" opened from my custom block.. 

Hm, do the images appear in the custom block's Media Library in the English version, but not the Polish version?

**Comment by robs23** [comment]
That's kind of what it is. More over, the file that appears in English post (and REFUSE to appear in Polish) has language set to "Polish" in "Media Library" file details.. So in the nutshell:

English version (both working well):
-  "foto" field of my block: https://aska-knives.pl/wp-content/uploads/2019/06/TRAPER-1.jpg
-  featured image: https://aska-knives.pl/wp-content/uploads/2019/06/TRAPER-6.jpg

Polish version:
- "foto" field of my block: can't set it to TRAPER-6.jpg neither TRAPER-1.jpg as none of the file can be found in block's "Media Library"
- featured image: https://aska-knives.pl/wp-content/uploads/2019/06/TRAPER-6.jpg (working well)

In the file details both TRAPER-6 and TRAPER-1 are set to Polish..

**Comment by kienstra** [comment]
Hi @robs23,
Thanks for your details. I'm not sure if I'll be able to debug that.

Are you using a translation plugin?

**Comment by robs23** [comment]
I used Polylang plugin to create the translations. All the translations were done last year and it hasn't been such a problem until around 2 months ago. For that reason I don't think it's the culprit here..

**Comment by kienstra** [comment]
OK, so it looks like there's an English and Polish version of each URL, like:

https://aska-knives.pl/en/about-me/
https://aska-knives.pl/o-mnie/

It's going to be really hard for me to debug this. I'm not sure why it's working in English and not in Polish. 

Is there a difference between those that could cause it not to work?

Maybe:

>...has language set to "Polish" in "Media Library" file details..

**Comment by kienstra** [comment]
>The thing is all the media files ARE there in the media library, it's just only that I can't find them in "Media library" opened from my custom block.. 

In the Polish version, are the images available on that page in the Media Library of a core Image block?

![image-block](https://user-images.githubusercontent.com/4063887/86492985-6b56fa00-bd35-11ea-99c0-d1dfb0c0f674.png)


![core-image-block](https://user-images.githubusercontent.com/4063887/86492738-b8869c00-bd34-11ea-85c5-4c86b179c48d.png)

**Comment by robs23** [comment]
No, they are not. I get it, in other words you're saying it's not issue of your plugin and you are right. I'll seek the answer elsewhere, thanks for all the pointers.

**Comment by kienstra** [comment]
Thanks, @robs23. I wish I could be more helpful.
