### ISSUE TITLE
JSON error from URL in block

### ISSUE THREAD

**Issue by sahayw** [getblocklab/block-lab#683]
## Bug summary

Including URL in block causes JSON error in Editor preview

## Steps to reproduce

Create block including URL (can be in text field or URL type)
Block edit and front-end work fine. Preview in editor throws JSON error.

## Expected behavior
Preview to show similar to front-end

## Actual behavior
<img width="1187" alt="Screen Shot 2020-08-12 at 10 54 17 AM" src="https://user-images.githubusercontent.com/19331248/90051667-e55f9480-dc8c-11ea-81e4-b0679bb7c2d6.png">
<img width="1187" alt="Screen Shot 2020-08-12 at 11 15 19 AM" src="https://user-images.githubusercontent.com/19331248/90051832-23f54f00-dc8d-11ea-9677-d86771bedec0.png">
<img width="1082" alt="Screen Shot 2020-08-12 at 11 16 52 AM" src="https://user-images.githubusercontent.com/19331248/90051953-58690b00-dc8d-11ea-9e3c-9f5f0a810edd.png">

## Additional information
ASTRA theme, minimal plug-ins but includes Atomic Blocks and Ultimate Gutenberg

If put "foo" in url field then preview works but gives https://sitename/wp-admin/foo as the URL.

## Versions

 - WordPress version:  5.5 (also 5.4)
 - Block Lab version: 1.5.5
 - Gutenberg plugin version (if active):  Tried prior to 5.5 but no difference 
 - OS: MacOS 10.15.6
 - Browser: Brave 1.3.115
 - Device:

**Comment by kienstra** [comment]
Hi @sahayw,
Thanks for opening this and sharing your details. I'll test it.

**Comment by kienstra** [comment]
Hi @sahayw,
Could you please paste the block's PHP template here?

The block [shown above](https://github.com/getblocklab/block-lab/issues/683#issue-677902266) works well in my local with WP 5.5 and BL 1.5.5:

![block-with-url](https://user-images.githubusercontent.com/4063887/90057725-6d9e6380-dca6-11ea-8b18-53c9b318fccd.gif)

**Comment by sahayw** [comment]
<div id="readings">
    <span id="post-date"> <?php echo get_the_date() ?> </span>
    <span id="readings-value"> Readings: <em> <?php block_field('readings') ?> </em> </span>
    <span id="readings-link"><a href=" <?php esc_url(block_field('lectionary')) ?> " target=_blank>Link to Lectionary</a></span>
</div>

**Comment by kienstra** [comment]
Thanks!

**Comment by kienstra** [comment]
Here's what the block editor preview looks like in my local:

<img width="954" alt="readings" src="https://user-images.githubusercontent.com/4063887/90058653-9f63fa00-dca7-11ea-80d7-c7e51f65b623.png">

**Comment by kienstra** [comment]
Could you please try deactivating all plugins expect Block Lab? 

Though I tested it with Atomic Blocks and Ultimate Gutenberg, and it still worked fine.

**Comment by sahayw** [comment]
That’s a bit of a mystery. I’ll try deactivating although there isn’t much there. Won’t be immediate since I’m in the middle of something else.

Thanks for your help.

**Comment by kienstra** [comment]
OK, thanks for your patience.

If that doesn't work, could you please paste the network request Header and Response here:

![copy-and-paste](https://user-images.githubusercontent.com/4063887/90059679-32516400-dca9-11ea-9933-3e4fce3a1fd1.gif)

**Comment by kienstra** [comment]
If you're up for it, I wonder if this bug happens on Firefox or Chrome. Though I suspect it's more back-end related.

**Comment by sahayw** [comment]
Deactivating other plugins made no difference.

Same results with Chrome and Safari. Can try Firefox if you want but like you say this isn't a browser issue.

HEADERS GENERAL
`Request URL: https://rciaspirituality.com/wp-json/wp/v2/block-renderer/block-lab/weekly-readings?context=edit&attributes%5Breadings%5D=Isa%2056%3A1%2C%206-7%3B%09Rom%2011%3A13-15%2C%2029-32%3B%09Matt%2015%3A21-28&attributes%5Blectionary%5D=http%3A%2F%2Fbible.usccb.org%2Fbible%2Freadings%2F081620.cfm&post_id=1221&_locale=user
Request Method: GET
Status Code: 406 
Remote Address: 66.235.200.146:443
Referrer Policy: strict-origin-when-cross-origin`

RESPONSE
`<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>`

**Comment by kienstra** [comment]
Hi @sahayw,
Nice, thanks a lot for pasting that.

Right, no need to try it in Firefox. It's probably not a browser issue.

From searching for that error message, it might be related to the server security:

https://wordpress.org/support/topic/not-acceptable-mod_security-error-after-i-hit-allow/

Would you be able to ask your hosting provider about that...if you're not self-hosting?

**Comment by sahayw** [comment]
Using Bluehost. Doesn't seem to allow for modifying Mod_security.

But realized that easiest way to sidestep the problem is to remove the initial "http" from the URL - since it gets preprended in browser anyway. (and make that field text rather than url type)

Just a thought - since other users including a URL in a block and thus in JSON would likely hit this issue if running Apache you might want to consider stripping the 'http(s):' when you store the data from URL field (and adding it back on output if you think that is necessary)

Thanks for helping debug this.

**Comment by kienstra** [comment]
Ah, good idea to remove the `http`. 

>Just a thought - since other users including a URL in a block and thus in JSON would likely hit this issue if running Apache you might want to consider stripping the 'http(s):' when you store the data from URL field (and adding it back on output if you think that is necessary)

Thanks, I'll think about that.

**Comment by kienstra** [comment]
If it's alright, I'm going to close this, as there's no immediate action.

**Comment by sahayw** [comment]
Sure. But I guess it would be worth posting something back on WP Forum to mention what we discovered and suggest the workaround. Seems likely someone else could hit the same issue. Shall I do that?

**Comment by kienstra** [comment]
Sure, that'd be great! Thanks a lot.
