### ISSUE TITLE
Fatal Error on Plugin Activation

### ISSUE THREAD

**Issue by RobStino** [getblocklab/block-lab#74]
`Plugin could not be activated because it triggered a fatal error.`

`Fatal error: Uncaught Error: Class 'AdvancedCustomBlocks\View\Admin_Menu' not found in /var/www/vhosts/acb.number11.co/httpdocs/wp-content/plugins/advanced-custom-blocks/advanced-custom-blocks.php:95 Stack trace: #0 /var/www/vhosts/acb.number11.co/httpdocs/wp-admin/includes/plugin.php(1897): include() #1 /var/www/vhosts/acb.number11.co/httpdocs/wp-admin/plugins.php(178): plugin_sandbox_scrape('advanced-custom...') #2 {main} thrown in /var/www/vhosts/acb.number11.co/httpdocs/wp-content/plugins/advanced-custom-blocks/advanced-custom-blocks.php on line 95`

- This is on a new WP install.
-  Plugin is v0.1 from the wp.org repo
- Default theme
- Not other plugins active
- PHP 7.1.20
- Has Let's Encrypt SSL Cert
- https://acb.number11.co/
- Apache

**Comment by lukecarbis** [comment]
Does the same error occur on the current `develop` branch? We changed a few things that might be related.

**Comment by RobStino** [comment]
This was on v1.0 that is up on wp.org. I'll test with the dev version.

**Comment by timbutler** [comment]
Can confirm the same error occurs with the wp.org 0.1 version but the activation works if using the dev branch from GitHub.

**Comment by rheinardkorf** [comment]
Thanks @timbutler

**Comment by RobStino** [comment]
Interestingly/coincidently, my dev server is with Conetix, which is @timbutler 's hosting company. :D So the bug may have been related to the hosting env, but if the dev branch sorts it out, then we're all good.
