### ISSUE TITLE
Hey psssst 👀 You might want to check this out

### ISSUE THREAD

**Issue by jcklpe** [getblocklab/block-lab#79]
I found this project before I found ya'll's. Ya'll's currently works for what I need but it looks like these guys also have a more expansive feature set in certain ways. 

Anway, thought you might want to check it out and maybe use some of it's code, or collaborate with the dev working on the project. 

https://github.com/rchipka/advanced-custom-blocks 

@rheinardkorf

**Comment by lukecarbis** [comment]
That's some great looking work, thanks for sharing! We're actually planning on renaming this project, so hopefully that gives @rchipka a little more room to shine!
